using SuperMetroid.Core.Frontend;

namespace SuperMetroid.Core.Assets;

/// <summary>Game-over Baby color inputs with calculated cry-phase brightness steps.</summary>
/// <remarks>
/// Original $82:BD97..BE16 contains four sixteen-color phases. Native $82:BB9F..BBB4
/// copies a selected phase to OBJ palette 4; $82:CFF6/CFFD/D004 select the fixed
/// 16x16 Baby images at OBJ tiles $90/$92/$9B from $B6:C000. Their pixel inks are
/// categorical materials, not samples of a numeric independent variable.
///
/// Calculate the green five-level ramp, floor midpoints for organ/fang shades,
/// warm/cyan five-level cry tints and subsequent saturated three-level brightness.
/// MiddleCry holds fang red; glass shade 13 is capped below highlight 14.
/// ClosedCry glass shade preserves Idle green and shares it with blue; its red is
/// an independent endpoint. The green cry endpoint shares red/blue. The darkest
/// glass tint preserves Idle red. Import stores only independently differing
/// target channels, so source and target artwork edits remain exact without a cache.
///
/// The remaining stock artwork inputs are ten visible Idle endpoint colors:
/// green 4, organs 6/8, outline 9, fangs 10/12, and glass 1/13/14/15; plus the
/// ClosedCry green red=1, glass red=16 and outline red=4 choices. Those 33 RGB5
/// components choose the depicted materials' hues and endpoint intensities. Fixed
/// sprite pixels select them directly; animation supplies only phase/frame, not
/// geometry, illumination or a quantity defining those endpoint colors. Fitting
/// categorical ink numbers would re-encode the painting, the #1165 nonsense
/// exception. The actual shade/phase relationships are calculated separately.
///
/// Two further Idle words are preserved unused artwork metadata: ink 0 is skipped
/// by OBJ transparency, and ink 5 occurs in none of the three native Baby images.
/// Their original values cannot be deduced from drawn pixels; inventing a function
/// for this non-drawn metadata would likewise only encode the arbitrary payload.
/// Stock storage is therefore twelve base words, two endpoint red fields and one
/// differing outline-red component. This narrow disposition covers this palette
/// only; it does not exempt other palette families or their numerical relationships.
/// </remarks>
internal sealed class GameOverBabyColorCatalog
{
    /// <summary>Supplied palette words whose phase/ink values are not generated by a color relationship.</summary>
    private readonly Dictionary<int, ushort> inputs = new();
    /// <summary>Per-channel corrections preserving source palette edits where calculated colors differ from authored targets.</summary>
    private readonly Dictionary<int, LoadingPaletteInputView.Channels> differences = new();
    /// <summary>Closed-cry green ink's authored red endpoint, shared by red and blue channels.</summary>
    private readonly int greenCryRed;
    /// <summary>Closed-cry glass ink's authored red endpoint, independent of its idle-derived green and blue.</summary>
    private readonly int glassCryRed;

    /// <summary>Captures values from the four named palettes already validated by the presentation loader.</summary>
    internal GameOverBabyColorCatalog(IReadOnlyDictionary<string, ushort[]> palettes)
    {
        ushort[] closed = palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.ClosedCry)];
        greenCryRed = closed[4] & 31;
        glassCryRed = closed[13] & 31;
        for (int phase = 0; phase < 4; phase++)
        for (int color = 0; color < 16; color++)
        {
            ushort supplied = palettes[GameOverPresentationDefinitions.BabyPaletteName((GameOverBabyPalette)phase)][color];
            int key = phase * 16 + color;
            bool greenShade = phase < 2 && color is 2 or 3;
            bool warmCry = phase == 1 && color is >= 5 and <= 12;
            bool middleShade = phase == 0 && color is 7 or 11;
            bool coolCry = phase == 1 && color is 1 or 15;
            bool greenCry = phase == 1 && color == 4;
            bool glassHighlight = phase == 1 && color == 14;
            bool glassCry = phase == 1 && color == 13;
            if (!greenShade && !warmCry && !middleShade && !coolCry && !greenCry && !glassHighlight && !glassCry &&
                (phase == 0 || (phase == 1 && color != 0)))
            {
                inputs.Add(key, supplied);
                continue;
            }
            ushort expected = glassCry
                ? GlassCry(palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color])
                : glassHighlight
                ? Brighten(palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color], 5)
                : coolCry
                ? CoolCry(palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color], color)
                : greenCry ? GreenCry(palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color])
                : middleShade
                ? MiddleShade(palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color - 1],
                    palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color + 1])
                : greenShade
                ? GreenShade(palettes[GameOverPresentationDefinitions.BabyPaletteName((GameOverBabyPalette)phase)][4], color)
                : warmCry ? WarmCry(palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][color])
                : color == 0
                ? palettes[GameOverPresentationDefinitions.BabyPaletteName(GameOverBabyPalette.Idle)][0]
                : CryShade(palettes[GameOverPresentationDefinitions.BabyPaletteName((GameOverBabyPalette)(phase - 1))][color],
                    phase, color, color == 13 ? palettes[GameOverPresentationDefinitions.BabyPaletteName((GameOverBabyPalette)phase)][14] : (ushort)0);
            if (supplied != expected)
                differences.Add(key, new(supplied, expected));
        }
    }

    /// <summary>Resolves a phase/ink color from retained palette inputs and the catalog's calculated relationships.</summary>
    /// <param name="palette">Game-over palette phase to read.</param>
    /// <param name="color">Zero-based ink index within the sixteen-color palette.</param>
    /// <returns>The BGR555 word after applying any preserved authored channel corrections.</returns>
    internal ushort Read(GameOverBabyPalette palette, int color)
    {
        _ = GameOverPresentationDefinitions.BabyPaletteName(palette);
        if ((uint)color >= 16) throw new IndexOutOfRangeException();
        int phase = (int)palette;
        int key = phase * 16 + color;
        if (inputs.TryGetValue(key, out ushort value)) return value;
        ushort expected = phase == 1 && color == 13
            ? GlassCry(Read(GameOverBabyPalette.Idle, color))
            : phase == 1 && color == 14
            ? Brighten(Read(GameOverBabyPalette.Idle, color), 5)
            : phase == 1 && color is 1 or 15
            ? CoolCry(Read(GameOverBabyPalette.Idle, color), color)
            : phase == 1 && color == 4 ? GreenCry(Read(GameOverBabyPalette.Idle, color))
            : phase == 0 && color is 7 or 11
            ? MiddleShade(Read(palette, color - 1), Read(palette, color + 1))
            : phase < 2 && color is 2 or 3
            ? GreenShade(Read(palette, 4), color)
            : phase == 1 && color is >= 5 and <= 12 ? WarmCry(Read(GameOverBabyPalette.Idle, color))
            : color == 0 ? inputs[0] : CryShade(Read((GameOverBabyPalette)(phase - 1), color),
                phase, color, color == 13 ? Read(palette, 14) : (ushort)0);
        return differences.TryGetValue(key, out var channels) ? channels.Apply(expected) : expected;
    }

    /// <summary>Derives one of the brighter green shades by raising only the green component from the darkest shade.</summary>
    /// <param name="darkest">Base green shade supplying red and blue components.</param>
    /// <param name="color">Ink index determining the green-channel step.</param>
    /// <returns>The packed BGR555 green shade.</returns>
    private static ushort GreenShade(ushort darkest, int color) =>
        (ushort)((darkest & 0x7c1f) | Math.Min(31, (darkest >> 5 & 31) + (4 - color) * 5) << 5);

    /// <summary>Creates the warm cry tint by raising red and lowering blue with saturation bounds.</summary>
    /// <param name="idle">Idle-phase color used as the tint source.</param>
    /// <returns>The packed warm cry color.</returns>
    private static ushort WarmCry(ushort idle) =>
        (ushort)(Math.Min(31, (idle & 31) + 5) | (idle & 0x03e0) |
            Math.Max(0, (idle >> 10 & 31) - 5) << 10);

    /// <summary>Creates the cool cry tint, with a special red-channel rule for the final glass ink.</summary>
    /// <param name="idle">Idle-phase color used as the tint source.</param>
    /// <param name="ink">Palette ink index selecting the final-ink red behavior.</param>
    /// <returns>The packed cool cry color.</returns>
    private static ushort CoolCry(ushort idle, int ink) =>
        (ushort)((WarmCry(idle) & 0x7c00) | (ink == 15 ? idle & 31 : Math.Min(31, (idle & 31) + 5)) |
            Math.Min(31, (idle >> 5 & 31) + 5) << 5);

    /// <summary>Builds the green cry color from the idle green channel and its authored shared red/blue endpoint.</summary>
    /// <param name="idle">Idle-phase green color supplying the source green intensity.</param>
    /// <returns>The packed green cry color.</returns>
    private ushort GreenCry(ushort idle) =>
        (ushort)(greenCryRed | Math.Min(31, (idle >> 5 & 31) + 5) << 5 | greenCryRed << 10);

    /// <summary>Builds the glass cry color while retaining idle green and sharing it with blue.</summary>
    /// <param name="idle">Idle-phase glass color supplying the shared green/blue channel.</param>
    /// <returns>The packed glass cry color.</returns>
    private ushort GlassCry(ushort idle) =>
        (ushort)(glassCryRed | (idle & 0x03e0) | (idle >> 5 & 31) << 10);

    /// <summary>Calculates a component-wise floor midpoint between bright and dark palette colors.</summary>
    /// <param name="bright">Brighter endpoint color.</param>
    /// <param name="dark">Darker endpoint color.</param>
    /// <returns>The packed BGR555 midpoint.</returns>
    private static ushort MiddleShade(ushort bright, ushort dark) =>
        (ushort)(((bright & 31) + (dark & 31)) / 2 |
            ((bright >> 5 & 31) + (dark >> 5 & 31)) / 2 << 5 |
            ((bright >> 10 & 31) + (dark >> 10 & 31)) / 2 << 10);

    /// <summary>Brightens a previous cry shade with fang-red preservation and a ceiling below the glass highlight.</summary>
    /// <param name="previous">Corresponding color from the prior cry phase.</param>
    /// <param name="phase">Current palette phase, used for the fang-specific channel rule.</param>
    /// <param name="ink">Ink index, used for fang and glass behavior.</param>
    /// <param name="highlight">Current glass highlight used as a strict upper bound for ink 13.</param>
    /// <returns>The packed calculated cry shade.</returns>
    private static ushort CryShade(ushort previous, int phase, int ink, ushort highlight)
    {
        ushort bright = Brighten(previous, 3);
        if (phase == 2 && ink is >= 10 and <= 12)
            return (ushort)((bright & 0x7fe0) | (previous & 31));
        if (ink == 13)
            return (ushort)(Math.Min(bright & 31, Math.Max(0, (highlight & 31) - 1)) |
                Math.Min(bright >> 5 & 31, Math.Max(0, (highlight >> 5 & 31) - 1)) << 5 |
                Math.Min(bright >> 10 & 31, Math.Max(0, (highlight >> 10 & 31) - 1)) << 10);
        return bright;
    }

    /// <summary>RGB5 additive brightness, saturating each component at 31 before packing.</summary>
    private static ushort Brighten(ushort color, int amount) =>
        (ushort)(Math.Min(31, (color & 31) + amount) |
            Math.Min(31, (color >> 5 & 31) + amount) << 5 |
            Math.Min(31, (color >> 10 & 31) + amount) << 10);
}
