using SuperMetroid.Core.Game;
using SuperMetroid.Core.Hardware;

namespace SuperMetroid.Core.Rooms;

/// <summary>Bank-$84's complete downward-gate PLM family.</summary>
public sealed partial class RoomPlmSystem
{
    /// <summary>Deferred enemy-projectile operations emitted by downward-gate setup and instruction execution.</summary>
    private readonly List<DownwardGateProjectileRequest> _downwardGateProjectileRequests = new();
    /// <summary>Sound requests generated by trigger shots, published with the room's PLM sound queue.</summary>
    private readonly List<PlmSoundRequest> _pendingDownwardGateSounds = new();
    /// <summary>Provider for the current Samus state used by gates that wake when she enters their column.</summary>
    private Func<SamusState?>? _downwardGateSamus;
    /// <summary>Active room width used to convert a gate block index into its column and row.</summary>
    private int _downwardGateRoomWidth;

    /// <summary>
    /// Returns and clears projectile work published by gate setup/list execution. Room load
    /// consumes the initial closed actor after enemy loading clears bank $86's pool; normal
    /// gameplay consumes later close/wake commands immediately after the PLM handler.
    /// </summary>
    public IReadOnlyList<DownwardGateProjectileRequest> TakeDownwardGateProjectileRequests()
    {
        DownwardGateProjectileRequest[] requests = _downwardGateProjectileRequests.ToArray();
        _downwardGateProjectileRequests.Clear();
        return requests;
    }

    /// <summary>Marks the five-cell gate column closed and queues its initial closed-gate projectile.</summary>
    /// <param name="level">Room blocks whose BTS values receive the closed-gate marker.</param>
    /// <param name="slot">Resident gate PLM supplying the column's starting block index.</param>
    private void SetupDownwardGateSlot(RoomLevelData level, PlmSlot slot)
    {
        slot.Gate = new DownwardGatePlmState();

        // Setup $C784 writes BTS $10 to the five vertically adjacent gate cells without
        // replacing their authored level words. C# block indexes are words, whereas the
        // native PLM index is a byte offset, so one room width here equals native +2*width.
        for (int row = 0; row < DownwardGatePlmRomData.GateHeightInBlocks; row++)
        {
            int blockIndex = checked(slot.BlockIndex + row * level.WidthInBlocks);
            _ = level.GetCollisionBlockByIndex(blockIndex);
            level.SetBehavior(blockIndex, DownwardGatePlmRomData.ClosedGateBts);
        }

        _downwardGateProjectileRequests.Add(new DownwardGateProjectileRequest(
            DownwardGateProjectileOperation.Spawn,
            (ushort)RoomEnemyProjectileKind.DownwardGateClosed,
            slot.BlockIndex));
    }

    /// <summary>Installs the shot-block list and any authored foreground blocks adjacent to a gate trigger.</summary>
    /// <param name="level">Room collision and foreground data receiving authored block words.</param>
    /// <param name="slot">Trigger PLM whose room argument selects the compiled shot-block definition.</param>
    private static void SetupDownwardGateShotBlock(RoomLevelData level, PlmSlot slot)
    {
        DownwardGateShotBlockDefinition definition =
            DownwardGateShotBlockDefinitions.Resolve(slot.RoomArgument);
        slot.InstructionPointer = definition.InstructionList;

        // Setup $C6E0 performs independent left and right writes even though every authored
        // row installs exactly one side. Preserve that ordering instead of deriving the side
        // from the trigger's low bit.
        if (definition.LeftBlockWord != 0)
            WriteDownwardGateShotBlock(level, slot.BlockIndex - 1, definition.LeftBlockWord);
        if (definition.RightBlockWord != 0)
            WriteDownwardGateShotBlock(level, slot.BlockIndex + 1, definition.RightBlockWord);
    }

    /// <summary>Writes one trigger-side foreground word and mirrors its low byte into block behavior data.</summary>
    /// <param name="level">Room data receiving the foreground word and BTS byte.</param>
    /// <param name="blockIndex">Room block index to update.</param>
    /// <param name="word">Authored foreground word whose low byte supplies the behavior value.</param>
    private static void WriteDownwardGateShotBlock(RoomLevelData level, int blockIndex, ushort word)
    {
        _ = level.GetCollisionBlockByIndex(blockIndex);
        level.SetForegroundEntry(blockIndex, word);
        level.SetBehavior(blockIndex, unchecked((byte)word));
    }

    /// <summary>Runs the shootable BTS $46-$4D dispatcher and wakes its adjacent gate.</summary>
    public bool TrySpawnDownwardGateTrigger(
        RoomLevelData level,
        int blockIndex,
        RoomBlockBehavior bts,
        SamusProjectileTypeWord projectileType)
    {
        ArgumentNullException.ThrowIfNull(level);
        if (!bts.TryGetDownwardGateTrigger(out DownwardGateTriggerBehavior trigger))
            return false;

        // Spawn_PLM still probes the fixed pool even though every trigger setup deletes its
        // temporary slot synchronously. A saturated pool therefore drops the collision just
        // as the cartridge does.
        PlmSlot? temporary = null;
        for (int index = _slots.Length - 1; index >= 0; index--)
        {
            if (_slots[index].Active)
                continue;
            temporary = _slots[index];
            ClearSlot(temporary);
            temporary.Active = true;
            temporary.HeaderPointer = HeaderForGateTrigger(trigger);
            temporary.BlockIndex = blockIndex;
            temporary.LoopTimer = projectileType.Raw;
            break;
        }
        if (temporary is null)
            return true;

        bool accepted = GateTriggerAcceptsProjectile(trigger, projectileType);
        if (!accepted)
        {
            if (trigger is not DownwardGateTriggerBehavior.BlueLeft and
                not DownwardGateTriggerBehavior.BlueRight)
            {
                _pendingDownwardGateSounds.Add(CreateSoundRequest(
                    SoundEffectId.FromCartridge(
                        SoundEffectLibrary.Library2,
                        DownwardGatePlmRomData.RejectedShotSound),
                    MaximumQueued: 6));
            }
            ClearSlot(temporary);
            return true;
        }

        int gateBlockIndex = IsLeftTrigger(trigger) ? blockIndex + 1 : blockIndex - 1;
        PlmSlot? gate = null;
        for (int index = _slots.Length - 1; index >= 0; index--)
        {
            PlmSlot candidate = _slots[index];
            if (candidate.Active && candidate.Gate is not null &&
                candidate.BlockIndex == gateBlockIndex)
            {
                gate = candidate;
                break;
            }
        }
        if (gate is null)
        {
            ClearSlot(temporary);
            throw new InvalidDataException(
                $"Downward gate trigger block {blockIndex} has no adjacent resident gate at {gateBlockIndex}.");
        }

        // Trigger setup increments only a zero timer. Repeated accepted hits before the
        // resident pre-instruction runs do not accumulate extra close cycles.
        if (gate.LoopTimer == 0)
            gate.LoopTimer = 1;
        ClearSlot(temporary);
        return true;
    }

    /// <summary>Moves queued trigger-shot sounds into the room PLM sound request list and clears the pending queue.</summary>
    private void PublishPendingDownwardGateSounds()
    {
        _soundRequests.AddRange(_pendingDownwardGateSounds);
        _pendingDownwardGateSounds.Clear();
    }

    /// <summary>Advances a gate's instruction pointer when its trigger or Samus-position wake condition is met.</summary>
    /// <param name="slot">Resident gate PLM whose pre-instruction and instruction state may be updated.</param>
    private void RunDownwardGatePreInstruction(PlmSlot slot)
    {
        if (slot.Gate is null)
            return;

        bool wake = slot.PreInstruction switch
        {
            0 or DownwardGatePreInstructionCodes.Inert => false,
            DownwardGatePreInstructionCodes.WakeIfTriggered => slot.LoopTimer != 0,
            DownwardGatePreInstructionCodes.WakeIfTriggeredOrSamusBelow =>
                slot.LoopTimer != 0 || IsSamusInsideDownwardGateColumn(slot),
            _ => throw new InvalidDataException(
                $"Downward gate reached untranslated pre-instruction $84:{slot.PreInstruction:X4}."),
        };
        if (!wake)
            return;

        slot.InstructionPointer = unchecked((ushort)(slot.InstructionPointer + 2));
        slot.InstructionTimer = 1;
        slot.PreInstruction = DownwardGatePreInstructionCodes.Inert;
    }

    /// <summary>Tests whether Samus occupies the gate's horizontal block column and five-block vertical span.</summary>
    /// <param name="slot">Gate PLM whose room block index identifies the tested column.</param>
    /// <returns><see langword="true"/> when the current Samus position is inside that gate region.</returns>
    private bool IsSamusInsideDownwardGateColumn(PlmSlot slot)
    {
        SamusState? samus = _downwardGateSamus?.Invoke();
        if (samus is null)
            return false;
        if (_downwardGateRoomWidth <= 0)
            throw new InvalidOperationException("Downward gate has no active room width.");
        int gateX = slot.BlockIndex % _downwardGateRoomWidth;
        int gateY = slot.BlockIndex / _downwardGateRoomWidth;
        return (samus.XPosition >> 4) == gateX &&
            unchecked((ushort)((samus.YPosition >> 4) - gateY)) <
                DownwardGatePlmRomData.GateHeightInBlocks;
    }

    /// <summary>Decodes the trigger identity's low bit to distinguish left-side gate triggers.</summary>
    /// <param name="trigger">Downward-gate trigger behavior identity.</param>
    /// <returns><see langword="true"/> for a left trigger.</returns>
    private static bool IsLeftTrigger(DownwardGateTriggerBehavior trigger) =>
        ((byte)trigger & 1) == 0;

    /// <summary>Maps a trigger behavior to its bank-$84 PLM header identity.</summary>
    /// <param name="trigger">Trigger behavior selecting the color and side-specific PLM.</param>
    /// <returns>The native header pointer for that trigger.</returns>
    /// <exception cref="ArgumentOutOfRangeException">The behavior is not a supported downward-gate trigger.</exception>
    private static ushort HeaderForGateTrigger(DownwardGateTriggerBehavior trigger) => trigger switch
    {
        DownwardGateTriggerBehavior.GreenLeft => DownwardGateTriggerPlmHeaders.GreenLeft,
        DownwardGateTriggerBehavior.GreenRight => DownwardGateTriggerPlmHeaders.GreenRight,
        DownwardGateTriggerBehavior.RedLeft => DownwardGateTriggerPlmHeaders.RedLeft,
        DownwardGateTriggerBehavior.RedRight => DownwardGateTriggerPlmHeaders.RedRight,
        DownwardGateTriggerBehavior.BlueLeft => DownwardGateTriggerPlmHeaders.BlueLeft,
        DownwardGateTriggerBehavior.BlueRight => DownwardGateTriggerPlmHeaders.BlueRight,
        DownwardGateTriggerBehavior.YellowLeft => DownwardGateTriggerPlmHeaders.YellowLeft,
        DownwardGateTriggerBehavior.YellowRight => DownwardGateTriggerPlmHeaders.YellowRight,
        _ => throw new ArgumentOutOfRangeException(nameof(trigger), trigger, null),
    };

    /// <summary>Applies each colored gate trigger's native projectile-family admission rule.</summary>
    /// <param name="trigger">Gate trigger whose projectile rule is being evaluated.</param>
    /// <param name="projectileType">Encoded projectile identity, including payload flags.</param>
    /// <returns>Whether this projectile activates the selected trigger.</returns>
    private static bool GateTriggerAcceptsProjectile(
        DownwardGateTriggerBehavior trigger,
        SamusProjectileTypeWord projectileType)
    {
        bool plainMissile = projectileType.HasPlainFamilyPayload(SamusProjectileFamily.Missile);
        bool plainSuper = projectileType.HasPlainFamilyPayload(SamusProjectileFamily.SuperMissile);
        bool plainPowerBomb = projectileType.HasPlainFamilyPayload(SamusProjectileFamily.PowerBomb);
        return trigger switch
        {
            DownwardGateTriggerBehavior.GreenLeft or DownwardGateTriggerBehavior.GreenRight => plainSuper,
            DownwardGateTriggerBehavior.RedLeft or DownwardGateTriggerBehavior.RedRight => plainMissile || plainSuper,
            DownwardGateTriggerBehavior.BlueLeft or DownwardGateTriggerBehavior.BlueRight => !plainPowerBomb,
            DownwardGateTriggerBehavior.YellowLeft => plainPowerBomb,

            // The retail right-yellow routine branches on BNE rather than BEQ. Preserve
            // that cartridge asymmetry even though it looks like a likely original bug.
            DownwardGateTriggerBehavior.YellowRight => !plainPowerBomb,
            _ => false,
        };
    }

    /// <summary>Marker state identifying a resident PLM slot as a downward gate.</summary>
    private sealed class DownwardGatePlmState;
}
