#nullable enable
using SuperMetroid.Core.Game;

namespace SuperMetroid.Core.Rooms;

/// <summary>Explicit ordered room-scroll state writes; regenerate with tools/generate-room-plm-population-definitions.ps1.</summary>
internal static partial class RoomPlmScrollProgramDefinitions
{
    internal static bool TryApply(ushort pointer, Action<int, RoomScrollState>? write)
    {
        switch (pointer)
        {
            case 0x92B0:
                write?.Invoke(19, RoomScrollState.Blue);
                return true;
            case 0x9389:
                write?.Invoke(8, RoomScrollState.Green);
                return true;
            case 0x938C:
                write?.Invoke(8, RoomScrollState.RedBoundary);
                return true;
            case 0x938F:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                write?.Invoke(2, RoomScrollState.RedBoundary);
                write?.Invoke(6, RoomScrollState.Green);
                return true;
            case 0x9396:
                write?.Invoke(6, RoomScrollState.RedBoundary);
                return true;
            case 0x9399:
                write?.Invoke(0, RoomScrollState.Blue);
                return true;
            case 0x939C:
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0x939F:
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0x93A2:
                write?.Invoke(4, RoomScrollState.RedBoundary);
                return true;
            case 0x93A5:
                write?.Invoke(4, RoomScrollState.RedBoundary);
                write?.Invoke(8, RoomScrollState.Green);
                return true;
            case 0x94C2:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(4, RoomScrollState.Green);
                return true;
            case 0x94C7:
                write?.Invoke(1, RoomScrollState.Blue);
                write?.Invoke(4, RoomScrollState.RedBoundary);
                return true;
            case 0x94FA:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0x9658:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0x968C:
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0x9744:
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0x9747:
                write?.Invoke(2, RoomScrollState.RedBoundary);
                return true;
            case 0x974A:
                write?.Invoke(23, RoomScrollState.Blue);
                return true;
            case 0x974D:
                write?.Invoke(23, RoomScrollState.RedBoundary);
                return true;
            case 0x9750:
                write?.Invoke(24, RoomScrollState.Blue);
                return true;
            case 0x9753:
                write?.Invoke(24, RoomScrollState.RedBoundary);
                return true;
            case 0x9756:
                write?.Invoke(25, RoomScrollState.Blue);
                return true;
            case 0x9759:
                write?.Invoke(25, RoomScrollState.RedBoundary);
                return true;
            case 0x97AB:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0x97B0:
                write?.Invoke(0, RoomScrollState.Blue);
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0x9801:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0x9966:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0x99F3:
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0x99F6:
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0x9B46:
                write?.Invoke(28, RoomScrollState.Green);
                write?.Invoke(29, RoomScrollState.RedBoundary);
                return true;
            case 0x9B4B:
                write?.Invoke(28, RoomScrollState.RedBoundary);
                write?.Invoke(29, RoomScrollState.Blue);
                write?.Invoke(41, RoomScrollState.Blue);
                return true;
            case 0x9B52:
                write?.Invoke(24, RoomScrollState.Green);
                write?.Invoke(28, RoomScrollState.Green);
                write?.Invoke(29, RoomScrollState.RedBoundary);
                write?.Invoke(41, RoomScrollState.RedBoundary);
                return true;
            case 0x9B98:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0x9BF9:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Green);
                return true;
            case 0x9C00:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                write?.Invoke(1, RoomScrollState.RedBoundary);
                write?.Invoke(2, RoomScrollState.RedBoundary);
                return true;
            case 0x9C32:
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0x9D11:
                write?.Invoke(11, RoomScrollState.Green);
                return true;
            case 0x9D14:
                write?.Invoke(4, RoomScrollState.Blue);
                write?.Invoke(11, RoomScrollState.RedBoundary);
                return true;
            case 0x9D84:
                write?.Invoke(32, RoomScrollState.Green);
                write?.Invoke(37, RoomScrollState.Green);
                write?.Invoke(38, RoomScrollState.Green);
                return true;
            case 0x9D8B:
                write?.Invoke(36, RoomScrollState.Green);
                return true;
            case 0x9D8E:
                write?.Invoke(29, RoomScrollState.RedBoundary);
                return true;
            case 0x9D91:
                write?.Invoke(28, RoomScrollState.Blue);
                write?.Invoke(29, RoomScrollState.Blue);
                return true;
            case 0x9D96:
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0x9D99:
                write?.Invoke(1, RoomScrollState.RedBoundary);
                return true;
            case 0x9E40:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.RedBoundary);
                write?.Invoke(2, RoomScrollState.Blue);
                write?.Invoke(3, RoomScrollState.Blue);
                return true;
            case 0x9E49:
                write?.Invoke(0, RoomScrollState.Blue);
                write?.Invoke(1, RoomScrollState.Blue);
                write?.Invoke(2, RoomScrollState.RedBoundary);
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0x9F05:
                write?.Invoke(18, RoomScrollState.Blue);
                return true;
            case 0x9F08:
                write?.Invoke(18, RoomScrollState.RedBoundary);
                return true;
            case 0x9F0B:
                write?.Invoke(13, RoomScrollState.Green);
                return true;
            case 0x9F0E:
                write?.Invoke(13, RoomScrollState.RedBoundary);
                return true;
            case 0x9F5F:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0x9FB7:
                write?.Invoke(5, RoomScrollState.Green);
                return true;
            case 0xA04A:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(5, RoomScrollState.Blue);
                write?.Invoke(6, RoomScrollState.Blue);
                return true;
            case 0xA104:
                write?.Invoke(0, RoomScrollState.Blue);
                return true;
            case 0xA28E:
                write?.Invoke(6, RoomScrollState.Green);
                write?.Invoke(7, RoomScrollState.Green);
                return true;
            case 0xA36F:
                write?.Invoke(15, RoomScrollState.Green);
                write?.Invoke(18, RoomScrollState.Green);
                return true;
            case 0xA374:
                write?.Invoke(10, RoomScrollState.Blue);
                write?.Invoke(9, RoomScrollState.Green);
                return true;
            case 0xA379:
                write?.Invoke(10, RoomScrollState.RedBoundary);
                return true;
            case 0xA3A9:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0xA3DA:
                write?.Invoke(0, RoomScrollState.Blue);
                return true;
            case 0xA439:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xA43E:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                write?.Invoke(1, RoomScrollState.RedBoundary);
                write?.Invoke(2, RoomScrollState.Blue);
                write?.Invoke(3, RoomScrollState.Blue);
                return true;
            case 0xA4A2:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Blue);
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0xA4A9:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0xA4AE:
                write?.Invoke(3, RoomScrollState.Blue);
                return true;
            case 0xA50F:
                write?.Invoke(1, RoomScrollState.Blue);
                write?.Invoke(5, RoomScrollState.RedBoundary);
                return true;
            case 0xA514:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(5, RoomScrollState.Blue);
                return true;
            case 0xA519:
                write?.Invoke(5, RoomScrollState.RedBoundary);
                return true;
            case 0xA51C:
                write?.Invoke(3, RoomScrollState.Blue);
                write?.Invoke(5, RoomScrollState.RedBoundary);
                return true;
            case 0xA59C:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0xA6D6:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0xA6D9:
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xA6DC:
                write?.Invoke(0, RoomScrollState.Blue);
                return true;
            case 0xA6DF:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                return true;
            case 0xA860:
                write?.Invoke(17, RoomScrollState.Green);
                write?.Invoke(24, RoomScrollState.Blue);
                return true;
            case 0xA8EC:
                write?.Invoke(3, RoomScrollState.Blue);
                return true;
            case 0xA8EF:
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0xA8F2:
                write?.Invoke(2, RoomScrollState.Green);
                return true;
            case 0xA8F5:
                write?.Invoke(2, RoomScrollState.RedBoundary);
                return true;
            case 0xA980:
                write?.Invoke(25, RoomScrollState.Green);
                write?.Invoke(37, RoomScrollState.Green);
                write?.Invoke(38, RoomScrollState.Green);
                return true;
            case 0xA987:
                write?.Invoke(37, RoomScrollState.Green);
                return true;
            case 0xA98A:
                write?.Invoke(37, RoomScrollState.RedBoundary);
                return true;
            case 0xAA70:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Green);
                return true;
            case 0xAA75:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Green);
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0xAA7C:
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0xAA7F:
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0xACB0:
                write?.Invoke(0, RoomScrollState.Blue);
                return true;
            case 0xADA7:
                write?.Invoke(1, RoomScrollState.RedBoundary);
                return true;
            case 0xADAA:
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0xAE66:
                write?.Invoke(6, RoomScrollState.Blue);
                write?.Invoke(7, RoomScrollState.Blue);
                return true;
            case 0xAE6B:
                write?.Invoke(8, RoomScrollState.Blue);
                return true;
            case 0xAE6E:
                write?.Invoke(8, RoomScrollState.RedBoundary);
                return true;
            case 0xAE71:
                write?.Invoke(7, RoomScrollState.RedBoundary);
                return true;
            case 0xAEA9:
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0xAEAC:
                write?.Invoke(2, RoomScrollState.RedBoundary);
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0xAEB1:
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0xAF0F:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xAF6F:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0xB0A7:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xB0AC:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0xB0B1:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                return true;
            case 0xB224:
                write?.Invoke(3, RoomScrollState.Green);
                write?.Invoke(4, RoomScrollState.Green);
                write?.Invoke(6, RoomScrollState.Green);
                write?.Invoke(7, RoomScrollState.Green);
                return true;
            case 0xB22D:
                write?.Invoke(4, RoomScrollState.RedBoundary);
                write?.Invoke(6, RoomScrollState.Blue);
                write?.Invoke(7, RoomScrollState.Blue);
                write?.Invoke(8, RoomScrollState.Blue);
                return true;
            case 0xB27D:
                write?.Invoke(12, RoomScrollState.Green);
                return true;
            case 0xB280:
                write?.Invoke(12, RoomScrollState.RedBoundary);
                return true;
            case 0xB2D1:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Blue);
                write?.Invoke(3, RoomScrollState.Blue);
                return true;
            case 0xB3D9:
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xB3DC:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0xB445:
                write?.Invoke(6, RoomScrollState.Blue);
                return true;
            case 0xB448:
                write?.Invoke(6, RoomScrollState.RedBoundary);
                return true;
            case 0xB44B:
                write?.Invoke(7, RoomScrollState.Blue);
                return true;
            case 0xB44E:
                write?.Invoke(7, RoomScrollState.RedBoundary);
                return true;
            case 0xB451:
                write?.Invoke(14, RoomScrollState.Blue);
                return true;
            case 0xB454:
                write?.Invoke(14, RoomScrollState.RedBoundary);
                return true;
            case 0xB4E0:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xB547:
                write?.Invoke(1, RoomScrollState.Blue);
                write?.Invoke(2, RoomScrollState.Blue);
                write?.Invoke(6, RoomScrollState.RedBoundary);
                return true;
            case 0xB54E:
                write?.Invoke(1, RoomScrollState.RedBoundary);
                write?.Invoke(2, RoomScrollState.RedBoundary);
                write?.Invoke(6, RoomScrollState.Blue);
                return true;
            case 0xB555:
                write?.Invoke(3, RoomScrollState.Blue);
                write?.Invoke(4, RoomScrollState.Green);
                return true;
            case 0xB5C3:
                write?.Invoke(10, RoomScrollState.Green);
                write?.Invoke(13, RoomScrollState.Green);
                return true;
            case 0xB5C8:
                write?.Invoke(10, RoomScrollState.RedBoundary);
                write?.Invoke(13, RoomScrollState.RedBoundary);
                return true;
            case 0xB5CD:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(3, RoomScrollState.Green);
                return true;
            case 0xB5D2:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0xB612:
                write?.Invoke(7, RoomScrollState.Green);
                return true;
            case 0xB615:
                write?.Invoke(1, RoomScrollState.Blue);
                write?.Invoke(7, RoomScrollState.RedBoundary);
                return true;
            case 0xB61A:
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0xB61D:
                write?.Invoke(0, RoomScrollState.Blue);
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0xB622:
                write?.Invoke(4, RoomScrollState.RedBoundary);
                return true;
            case 0xB625:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                return true;
            case 0xB628:
                write?.Invoke(1, RoomScrollState.RedBoundary);
                return true;
            case 0xB68D:
                write?.Invoke(9, RoomScrollState.RedBoundary);
                return true;
            case 0xB690:
                write?.Invoke(8, RoomScrollState.Blue);
                write?.Invoke(9, RoomScrollState.Blue);
                return true;
            case 0xB695:
                write?.Invoke(8, RoomScrollState.RedBoundary);
                return true;
            case 0xB72D:
                write?.Invoke(11, RoomScrollState.Blue);
                return true;
            case 0xB730:
                write?.Invoke(11, RoomScrollState.Green);
                write?.Invoke(13, RoomScrollState.Green);
                write?.Invoke(14, RoomScrollState.Green);
                return true;
            case 0xB737:
                write?.Invoke(0, RoomScrollState.Blue);
                write?.Invoke(4, RoomScrollState.RedBoundary);
                return true;
            case 0xB73C:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(4, RoomScrollState.Green);
                return true;
            case 0xC9EC:
                write?.Invoke(14, RoomScrollState.Blue);
                write?.Invoke(15, RoomScrollState.Blue);
                return true;
            case 0xC9F1:
                write?.Invoke(4, RoomScrollState.RedBoundary);
                write?.Invoke(5, RoomScrollState.Green);
                write?.Invoke(11, RoomScrollState.Green);
                write?.Invoke(16, RoomScrollState.Blue);
                write?.Invoke(17, RoomScrollState.Blue);
                return true;
            case 0xCB7A:
                write?.Invoke(33, RoomScrollState.Blue);
                return true;
            case 0xCB7D:
                write?.Invoke(41, RoomScrollState.Blue);
                return true;
            case 0xCB80:
                write?.Invoke(33, RoomScrollState.RedBoundary);
                return true;
            case 0xCB83:
                write?.Invoke(41, RoomScrollState.RedBoundary);
                return true;
            case 0xCB86:
                write?.Invoke(40, RoomScrollState.Green);
                write?.Invoke(46, RoomScrollState.Green);
                return true;
            case 0xCC24:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0xCCC0:
                write?.Invoke(3, RoomScrollState.Blue);
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0xCCC5:
                write?.Invoke(3, RoomScrollState.RedBoundary);
                return true;
            case 0xCE3D:
                write?.Invoke(3, RoomScrollState.Blue);
                return true;
            case 0xCF4C:
                write?.Invoke(0, RoomScrollState.Green);
                return true;
            case 0xCF4F:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Green);
                return true;
            case 0xCFB5:
                write?.Invoke(0, RoomScrollState.Blue);
                write?.Invoke(1, RoomScrollState.RedBoundary);
                write?.Invoke(4, RoomScrollState.RedBoundary);
                return true;
            case 0xCFBC:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0xCFC1:
                write?.Invoke(0, RoomScrollState.RedBoundary);
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0xCFC6:
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0xD012:
                write?.Invoke(7, RoomScrollState.Blue);
                write?.Invoke(10, RoomScrollState.RedBoundary);
                return true;
            case 0xD052:
                write?.Invoke(10, RoomScrollState.Green);
                return true;
            case 0xD135:
                write?.Invoke(2, RoomScrollState.Green);
                return true;
            case 0xD138:
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0xD16A:
                write?.Invoke(4, RoomScrollState.Blue);
                return true;
            case 0xD1A0:
                write?.Invoke(5, RoomScrollState.Blue);
                return true;
            case 0xD1D8:
                write?.Invoke(4, RoomScrollState.Green);
                write?.Invoke(6, RoomScrollState.Blue);
                return true;
            case 0xD216:
                write?.Invoke(10, RoomScrollState.Green);
                return true;
            case 0xD219:
                write?.Invoke(10, RoomScrollState.RedBoundary);
                return true;
            case 0xD24D:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Blue);
                return true;
            case 0xD4BD:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xD67D:
                write?.Invoke(2, RoomScrollState.Green);
                write?.Invoke(3, RoomScrollState.RedBoundary);
                write?.Invoke(4, RoomScrollState.Green);
                write?.Invoke(5, RoomScrollState.RedBoundary);
                write?.Invoke(6, RoomScrollState.Blue);
                write?.Invoke(7, RoomScrollState.RedBoundary);
                return true;
            case 0xD68A:
                write?.Invoke(2, RoomScrollState.RedBoundary);
                write?.Invoke(3, RoomScrollState.Green);
                write?.Invoke(4, RoomScrollState.RedBoundary);
                write?.Invoke(5, RoomScrollState.Blue);
                write?.Invoke(6, RoomScrollState.RedBoundary);
                return true;
            case 0xD695:
                write?.Invoke(5, RoomScrollState.Green);
                write?.Invoke(7, RoomScrollState.Blue);
                return true;
            case 0xD6C8:
                write?.Invoke(1, RoomScrollState.Green);
                return true;
            case 0xD6CB:
                write?.Invoke(1, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Blue);
                return true;
            case 0xD7DF:
                write?.Invoke(0, RoomScrollState.Green);
                write?.Invoke(2, RoomScrollState.Green);
                return true;
            case 0xD951:
                write?.Invoke(5, RoomScrollState.RedBoundary);
                write?.Invoke(11, RoomScrollState.Blue);
                return true;
            case 0xD956:
                write?.Invoke(5, RoomScrollState.Blue);
                write?.Invoke(11, RoomScrollState.RedBoundary);
                return true;
            case 0xD95B:
                write?.Invoke(10, RoomScrollState.Blue);
                return true;
            default: return false;
        }
    }
}
