namespace SuperMetroid.Core.Rooms;

/// <summary>Named retail header dispatch; regenerate with tools/generate-room-plm-population-definitions.ps1 -HeadersOnly.</summary>
internal static partial class RoomPlmHeaderDefinitions
{
    private static bool TrySelect(ushort header, out RoomPlmHeaderDefinition value)
    {
        value = header switch
        {
            RoomPlmHeaders.RightwardsScrollExtension => new(header, 0xB33A, 0xAFA4),
            RoomPlmHeaders.LeftwardsScrollExtension => new(header, 0xB345, 0xAF9E),
            RoomPlmHeaders.DownwardsScrollExtension => new(header, 0xB350, 0xAFB0),
            RoomPlmHeaders.UpwardsScrollExtension => new(header, 0xB35B, 0xAFAA),
            RoomPlmHeaders.MapStation => new(header, 0xB18B, 0xAD62),
            RoomPlmHeaders.EnergyStation => new(header, 0xB21D, 0xADC2),
            RoomPlmHeaders.MissileStation => new(header, 0xB245, 0xAE4C),
            RoomPlmHeaders.ScrollTrigger => new(header, 0xB371, 0xAF86),
            RoomPlmHeaders.ElevatorPlatform => new(header, 0xB3C1, 0xAFB6),
            RoomPlmHeaders.SaveStation => new(header, 0xB5EE, 0xAFE8),
            RoomPlmHeaders.SpeedBoosterEscape => new(header, 0xB89C, 0xB88A),
            RoomPlmHeaders.BombTorizoGreyDoor => new(header, 0xC794, 0xBA7F),
            RoomPlmHeaders.WreckedShipAttic => new(header, 0xBAFA, 0xBAFF),
            RoomPlmHeaders.DownwardGate => new(header, 0xC6BE, 0xBC3A),
            RoomPlmHeaders.DownwardGateShotBlock => new(header, 0xC6E0, 0xBCAF),
            RoomPlmHeaders.GreyDoorFacingLeft => new(header, 0xC794, 0xBE70),
            RoomPlmHeaders.GreyDoorFacingRight => new(header, 0xC794, 0xBED9),
            RoomPlmHeaders.GreyDoorFacingUp => new(header, 0xC794, 0xBF42),
            RoomPlmHeaders.GreyDoorFacingDown => new(header, 0xC794, 0xBFAB),
            RoomPlmHeaders.YellowDoorFacingLeft => new(header, 0xC7B1, 0xC014),
            RoomPlmHeaders.YellowDoorFacingRight => new(header, 0xC7B1, 0xC077),
            RoomPlmHeaders.YellowDoorFacingUp => new(header, 0xC7B1, 0xC0DA),
            RoomPlmHeaders.YellowDoorFacingDown => new(header, 0xC7B1, 0xC139),
            RoomPlmHeaders.GreenDoorFacingLeft => new(header, 0xC7B1, 0xC19C),
            RoomPlmHeaders.GreenDoorFacingRight => new(header, 0xC7B1, 0xC1FB),
            RoomPlmHeaders.GreenDoorFacingUp => new(header, 0xC7B1, 0xC25A),
            RoomPlmHeaders.GreenDoorFacingDown => new(header, 0xC7B1, 0xC2B9),
            RoomPlmHeaders.RedDoorFacingLeft => new(header, 0xC7B1, 0xC318),
            RoomPlmHeaders.RedDoorFacingRight => new(header, 0xC7B1, 0xC37A),
            RoomPlmHeaders.MotherBrainEscapeRoomGate => new(header, 0xB3C1, 0xBB34),
            RoomPlmHeaders.MotherBrainGlass => new(header, 0xD5F6, 0xD202),
            RoomPlmHeaders.BombTorizoHand => new(header, 0xD606, 0xD368),
            RoomPlmHeaders.NoobTube => new(header, 0xD6CC, 0xD4D4),
            RoomPlmHeaders.SetMetroidsClearedStatesWhenRequired => new(header, 0xDB1E, 0xDB42),
            RoomPlmHeaders.EyeDoorEyeFacingRight => new(header, 0xDA8C, 0xD955),
            RoomPlmHeaders.EyeDoorFacingRight => new(header, 0xDAB9, 0xDA20),
            RoomPlmHeaders.EyeDoorBottomFacingRight => new(header, 0xDAB9, 0xDA56),
            RoomPlmHeaders.EyeDoorEyeFacingLeft => new(header, 0xDA8C, 0xD81E),
            RoomPlmHeaders.EyeDoorFacingLeft => new(header, 0xDAB9, 0xD8E9),
            RoomPlmHeaders.EyeDoorBottomFacingLeft => new(header, 0xDAB9, 0xD91F),
            RoomPlmHeaders.DraygonCannonFacingRight => new(header, 0xDE94, 0xDCDE),
            RoomPlmHeaders.DraygonCannonFacingRightDestroyed => new(header, 0xDF4C, 0xDD11),
            RoomPlmHeaders.DraygonCannonFacingLeft => new(header, 0xDEF0, 0xDDB9),
            RoomPlmHeaders.ExposedEnergyTank => new(header, 0xEE4D, 0xE099),
            RoomPlmHeaders.ExposedMissileTank => new(header, 0xEE52, 0xE0BE),
            RoomPlmHeaders.ExposedSuperMissileTank => new(header, 0xEE57, 0xE0E3),
            RoomPlmHeaders.ExposedPowerBombTank => new(header, 0xEE5C, 0xE108),
            RoomPlmHeaders.ExposedMorphBall => new(header, 0xEE64, 0xE3EF),
            RoomPlmHeaders.ChozoMissileTank => new(header, 0xEE52, 0xE47C),
            RoomPlmHeaders.ChozoSuperMissileTank => new(header, 0xEE57, 0xE4AE),
            RoomPlmHeaders.ChozoPowerBombTank => new(header, 0xEE5C, 0xE4E0),
            RoomPlmHeaders.ChozoBombs => new(header, 0xEE64, 0xE512),
            RoomPlmHeaders.ChozoChargeBeam => new(header, 0xEE64, 0xE54D),
            RoomPlmHeaders.ChozoIceBeam => new(header, 0xEE64, 0xE588),
            RoomPlmHeaders.ChozoHiJumpBoots => new(header, 0xEE64, 0xE5C3),
            RoomPlmHeaders.ChozoSpeedBooster => new(header, 0xEE64, 0xE5FE),
            RoomPlmHeaders.ChozoWaveBeam => new(header, 0xEE64, 0xE642),
            RoomPlmHeaders.ChozoSpazerBeam => new(header, 0xEE64, 0xE67D),
            RoomPlmHeaders.ChozoSpringBall => new(header, 0xEE64, 0xE6B8),
            RoomPlmHeaders.ChozoVariaSuit => new(header, 0xEE64, 0xE6F3),
            RoomPlmHeaders.ChozoGravitySuit => new(header, 0xEE64, 0xE735),
            RoomPlmHeaders.ChozoXrayScope => new(header, 0xEE64, 0xE777),
            RoomPlmHeaders.ChozoPlasmaBeam => new(header, 0xEE64, 0xE7B1),
            RoomPlmHeaders.ChozoGrappleBeam => new(header, 0xEE64, 0xE7EC),
            RoomPlmHeaders.ChozoSpaceJump => new(header, 0xEE64, 0xE826),
            RoomPlmHeaders.ChozoScrewAttack => new(header, 0xEE64, 0xE861),
            RoomPlmHeaders.ChozoReserveTank => new(header, 0xEE64, 0xE8D7),
            RoomPlmHeaders.ShotBlockEnergyTank => new(header, 0xEE77, 0xE911),
            RoomPlmHeaders.ShotBlockMissileTank => new(header, 0xEE7C, 0xE949),
            RoomPlmHeaders.ShotBlockSuperMissileTank => new(header, 0xEE81, 0xE981),
            _ => default,
        };
        return value.Header != 0;
    }
}
