using SuperMetroid.Core.Game;
using SuperMetroid.Core.Hardware;
using SuperMetroid.Core.Rooms;

/// <summary>Compares the shared AI against original-CPU output, including landing and reattachment.</summary>
internal static class CrawlerQuakeNativeAudit
{
    public static int Run(string rom, string csv)
    {
        byte[] trace = File.ReadAllBytes(csv);
        if (Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(trace)) != CrawlerNativeReference.TraceSha256)
            throw new InvalidDataException("Unrecognized original-CPU crawler trace.");
        string[] rows = File.ReadAllLines(csv);
        if (rows.Length != 241 || rows[0] != "ceiling,control,frame,x,xsub,y,ysub,function,return,vx,vy,fall,fallsub")
            throw new InvalidDataException("Incomplete original-CPU crawler trace.");
        int row = 1;
        for (int ceiling = 0; ceiling < 2; ceiling++)
        for (int control = 0; control < 3; control++)
        {
            var bus = SuperMetroidAddressSpace.LoadRetailRom(rom);
            var blocks = new ushort[256];
            for (int y = 0; y < 16; y++)
            for (int x = 0; x < 16; x++)
                blocks[y * 16 + x] = RoomLevelWord.Create(0, 0,
                    y == 6 || y == 12 || x == 6 ? RoomCollisionType.SolidBlock : RoomCollisionType.Air).Raw;
            var level = new RoomLevelData(16, 16, blocks, new byte[256], new ushort[256], []);
            var population = new PopulationSelectionAddressSpace(bus,
                [new RoomEnemyPopulationRecord(DownbackFixtureData.ZoomerDefinition, 120, 144,
                    0, (ushort)EnemyProperties.ProcessOffScreen, 0, 0, 0)]);
            var enemies = new RoomEnemySystem();
            enemies.Load(population, PopulationSelectionAddressSpace.PopulationPointer,
                PopulationSelectionAddressSpace.TilesetPointer, new SnesVram(), new SnesCgram(), () => 1);
            var actor = enemies.Slots[0];
            var state = enemies.CrawlerStates[0] ?? throw new InvalidDataException("Missing crawler state.");
            actor.XRadius = actor.YRadius = 8;
            actor.XPosition = ceiling != 0 ? (ushort)144 : (ushort)120;
            actor.YPosition = ceiling != 0 ? (ushort)120 : (ushort)144;
            state.XVelocity = ceiling != 0 ? (ushort)0 : unchecked((ushort)-128);
            state.YVelocity = ceiling != 0 ? unchecked((ushort)-128) : (ushort)0;
            state.Function = state.NonFallingFunction = ceiling != 0 ? CrawlerEnemyFunction.CrawlingHorizontally : CrawlerEnemyFunction.CrawlingVertically;
            for (int frame = 0; frame < 40; frame++)
            {
                enemies.EarthquakeTimer = frame != 0 ? (ushort)0 : (ushort)(SamusProjectileRomData.NonBeam.SuperMissileEarthquakeDuration - (control == 1 ? 1 : 0));
                enemies.EarthquakeType = control == 2 ? CrawlerQuakeAuditData.HorizontalQuakeControl : SamusProjectileRomData.NonBeam.SuperMissileEarthquakeType;
                enemies.StepFrame(0, 0, false, level: level);
                string actual = $"{ceiling},{control},{frame},{actor.XPosition:X4},{actor.XSubposition:X4},{actor.YPosition:X4},{actor.YSubposition:X4}," +
                    $"{(ushort)state.Function:X4},{(ushort)state.NonFallingFunction:X4},{state.XVelocity:X4},{state.YVelocity:X4},{state.FallingYVelocity:X4},{state.FallingYSubvelocity:X4}";
                if (actual != rows[row])
                    throw new InvalidDataException($"Crawler CPU mismatch row {row}: expected {rows[row]}, actual {actual}.");
                row++;
            }
        }
        Console.WriteLine("Crawler original CPU: 240 frames match detachment, 16.16 trajectory, landing, return function and velocity; adjacent quake controls match.");
        return 0;
    }
}

/// <summary>Accepted original-CPU capture generated by native-crawler-quake-probe.h.</summary>
internal static class CrawlerNativeReference
{
    /// <summary>SHA256 of the six-case, 240-frame CSV; no cartridge bytes are included in the capture.</summary>
    public const string TraceSha256 = "C73CA9BC272FE6C8383526213705E03146F3EF64456555BBDBAA1D3B5FA51C9D";
}
