namespace SuperMetroid.Core.Game;

/// <summary>Initial-health fractions generated by Kraid's native initialization.</summary>
internal static class KraidHealthThresholdDefinitions
{
    /// <summary>$A7:AA02-AA16: truncate health/8, then accumulate eight multiples.</summary>
    public static ushort Eighth(ushort initialHealth, int index)
    {
        if ((uint)index >= 8) throw new IndexOutOfRangeException();
        return (ushort)((initialHealth >> 3) * (index + 1));
    }

    /// <summary>$A7:AA23-AA43: truncate health/4, then accumulate four multiples.</summary>
    public static ushort Quarter(ushort initialHealth, int index)
    {
        if ((uint)index >= 4) throw new IndexOutOfRangeException();
        return (ushort)((initialHealth >> 2) * (index + 1));
    }
}
