using static SuperMetroid.Core.Game.InstructionItem;

namespace SuperMetroid.Core.Game;

internal readonly record struct RoomSpriteObjectInstructionMechanicsWord(
    ushort Address,
    ushort Value);

/// <summary>
/// Compiled engine-control words reachable from all 62 bank-$B4 room sprite-object
/// programs. Interleaved spritemap pointers remain live cartridge presentation data.
/// </summary>
internal static class RoomSpriteObjectInstructionProgramDefinitions
{
    /// <summary><c>SpriteObject_Instr_RepeatLast</c> at $B4:BCF0.</summary>
    public const ushort RepeatLast = 0xbcf0;

    /// <summary><c>SpriteObject_Instr_Terminate</c> at $B4:BD07.</summary>
    public const ushort Terminate = 0xbd07;

    /// <summary><c>SpriteObject_Instr_Goto</c> at $B4:BD12.</summary>
    public const ushort Goto = 0xbd12;

    /// <summary><c>UNUSED_InstList_SpriteObject_1C_ElevatorPad_B4BF68</c> at $B4:BF68.</summary>
    private const ushort UNUSEDInstListSpriteObject1CElevatorPadB4BF68 = 0xbf68;
    /// <summary><c>UNUSED_InstList_SpriteObject_1E_B4C198</c> at $B4:C198.</summary>
    private const ushort UNUSEDInstListSpriteObject1EB4C198 = 0xc198;
    /// <summary><c>UNUSED_InstList_SpriteObject_1F_B4C1AC</c> at $B4:C1AC.</summary>
    private const ushort UNUSEDInstListSpriteObject1FB4C1AC = 0xc1ac;
    /// <summary><c>UNUSED_InstList_SpriteObject_20_B4C1C0</c> at $B4:C1C0.</summary>
    private const ushort UNUSEDInstListSpriteObject20B4C1C0 = 0xc1c0;
    /// <summary><c>UNUSED_InstList_SpriteObject_21_B4C1D4</c> at $B4:C1D4.</summary>
    private const ushort UNUSEDInstListSpriteObject21B4C1D4 = 0xc1d4;
    /// <summary><c>UNUSED_InstList_SpriteObject_22_B4C1E8</c> at $B4:C1E8.</summary>
    private const ushort UNUSEDInstListSpriteObject22B4C1E8 = 0xc1e8;
    /// <summary><c>UNUSED_InstList_SpriteObject_23_B4C1FC</c> at $B4:C1FC.</summary>
    private const ushort UNUSEDInstListSpriteObject23B4C1FC = 0xc1fc;
    /// <summary><c>UNUSED_InstList_SpriteObject_24_B4C210</c> at $B4:C210.</summary>
    private const ushort UNUSEDInstListSpriteObject24B4C210 = 0xc210;
    /// <summary><c>UNUSED_InstList_SpriteObject_25_B4C224</c> at $B4:C224.</summary>
    private const ushort UNUSEDInstListSpriteObject25B4C224 = 0xc224;
    /// <summary><c>UNUSED_InstList_SpriteObject_26_B4C238</c> at $B4:C238.</summary>
    private const ushort UNUSEDInstListSpriteObject26B4C238 = 0xc238;
    /// <summary><c>UNUSED_InstList_SpriteObject_27_B4C258</c> at $B4:C258.</summary>
    private const ushort UNUSEDInstListSpriteObject27B4C258 = 0xc258;
    /// <summary><c>UNUSED_InstList_SpriteObject_28_B4C2A0</c> at $B4:C2A0.</summary>
    private const ushort UNUSEDInstListSpriteObject28B4C2A0 = 0xc2a0;
    /// <summary><c>UNUSED_InstList_SpriteObject_29_B4C2BC</c> at $B4:C2BC.</summary>
    private const ushort UNUSEDInstListSpriteObject29B4C2BC = 0xc2bc;
    /// <summary><c>InstList_SpriteObject_2B_PuromiBody</c> at $B4:C30A.</summary>
    private const ushort SpriteObject2BPuromiBody = 0xc30a;
    /// <summary><c>UNSUED_InstList_SpriteObject_31_MetroidInsides_B4C3A2</c> at $B4:C3A2.</summary>
    private const ushort UNSUEDInstListSpriteObject31MetroidInsidesB4C3A2 = 0xc3a2;
    /// <summary><c>UNUSED_InstList_SpriteObject_33_B4C436</c> at $B4:C436.</summary>
    private const ushort UNUSEDInstListSpriteObject33B4C436 = 0xc436;
    /// <summary><c>UNUSED_InstList_SpriteObject_35_B4C536</c> at $B4:C536.</summary>
    private const ushort UNUSEDInstListSpriteObject35B4C536 = 0xc536;
    /// <summary><c>UNUSED_InstList_SpriteObject_36_B4C5B2</c> at $B4:C5B2.</summary>
    private const ushort UNUSEDInstListSpriteObject36B4C5B2 = 0xc5b2;
    /// <summary><c>UNUSED_InstList_SpriteObject_3A_B4C5E4</c> at $B4:C5E4.</summary>
    private const ushort UNUSEDInstListSpriteObject3AB4C5E4 = 0xc5e4;
    /// <summary><c>InstList_SpriteObject_3B_EvirFacingLeft</c> at $B4:C608.</summary>
    private const ushort SpriteObject3BEvirFacingLeft = 0xc608;
    /// <summary><c>InstList_SpriteObject_3C_EvirFacingRight</c> at $B4:C61C.</summary>
    private const ushort SpriteObject3CEvirFacingRight = 0xc61c;

    /// <summary>Native program bank $B4.</summary>
    internal const byte Bank = 0xb4;

    private static readonly InstructionProgramLayout Layout = new(Bank,
        Origin(0xbe24),
        Frame(6),
        Frame(6),
        Frame(7),
        Frame(7),
        Frame(8),
        Frame(8),
        Frame(9),
        Frame(9),
        Op(Terminate),
        Origin(0xbe54),
        Frame(1),
        Op(RepeatLast),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Terminate),
        Frame(5),
        Frame(4),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Terminate),
        Frame(4),
        Frame(3),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(12),
        Op(Terminate),
        Frame(4),
        Frame(6),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(6),
        Op(Terminate),
        Frame(3),
        Frame(3),
        Frame(4),
        Frame(4),
        Frame(4),
        Op(Terminate),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(24),
        Op(Terminate),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Op(Terminate),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Terminate),
        Frame(1),
        Frame(1),
        Op(Terminate),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Terminate),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Terminate),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Terminate),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Op(Terminate),
        Frame(1),
        Frame(1),
        Op(Goto, UNUSEDInstListSpriteObject1CElevatorPadB4BF68),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Terminate),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Op(Terminate),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Op(Terminate),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Terminate),
        Frame(16),
        Frame(16),
        Frame(16),
        Op(Terminate),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op(Terminate),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op(Terminate),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(5),
        Op(Terminate),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Terminate),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Terminate),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Op(Terminate),
        Frame(1),
        Frame(1),
        Frame(1),
        Op(Terminate),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Terminate),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Op(Terminate),
        Frame(16),
        Frame(16),
        Frame(16),
        Frame(16),
        Frame(16),
        Frame(16),
        Frame(16),
        Frame(16),
        Op(Terminate),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Frame(4),
        Op(Terminate),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject1EB4C198),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject1FB4C1AC),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject20B4C1C0),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject21B4C1D4),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject22B4C1E8),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject23B4C1FC),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject24B4C210),
        Frame(5),
        Frame(5),
        Frame(5),
        Frame(5),
        Op(Goto, UNUSEDInstListSpriteObject25B4C224),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Op(Goto, UNUSEDInstListSpriteObject26B4C238),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(48),
        Op(Goto, UNUSEDInstListSpriteObject27B4C258),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Op(Goto, UNUSEDInstListSpriteObject28B4C2A0),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(48),
        Op(Goto, UNUSEDInstListSpriteObject29B4C2BC),
        Frame(1),
        Op(RepeatLast),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Goto, SpriteObject2BPuromiBody),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op(Terminate),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op(Terminate),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op(Terminate),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(Terminate),
        Frame(16),
        Frame(16),
        Frame(6),
        Frame(10),
        Frame(16),
        Op(Goto, UNSUEDInstListSpriteObject31MetroidInsidesB4C3A2),
        Frame(2),
        Frame(3),
        Frame(2),
        Frame(1),
        Frame(3),
        Frame(4),
        Frame(4),
        Frame(5),
        Frame(2),
        Frame(1),
        Frame(4),
        Frame(2),
        Frame(3),
        Frame(4),
        Frame(7),
        Frame(3),
        Frame(2),
        Frame(1),
        Frame(2),
        Frame(3),
        Frame(4),
        Frame(4),
        Frame(2),
        Frame(2),
        Frame(3),
        Frame(1),
        Frame(4),
        Frame(3),
        Frame(3),
        Frame(2),
        Frame(7),
        Frame(2),
        Frame(3),
        Frame(4),
        Frame(2),
        Frame(1),
        Frame(3),
        Frame(2),
        Frame(3),
        Frame(4),
        Frame(1),
        Frame(3),
        Frame(3),
        Frame(4),
        Frame(32),
        Frame(2),
        Frame(1),
        Frame(2),
        Frame(1),
        Frame(4),
        Frame(3),
        Frame(4),
        Frame(5),
        Frame(4),
        Frame(2),
        Frame(1),
        Frame(3),
        Frame(1),
        Frame(6),
        Frame(3),
        Frame(4),
        Frame(2),
        Op(Goto, UNUSEDInstListSpriteObject33B4C436),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Op(Goto, UNUSEDInstListSpriteObject35B4C536),
        Frame(16),
        Frame(16),
        Frame(16),
        Frame(16),
        Op(Goto, UNUSEDInstListSpriteObject36B4C5B2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op(Terminate),
        Frame(1),
        Op(RepeatLast),
        Frame(1),
        Op(RepeatLast),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Op(Goto, UNUSEDInstListSpriteObject3AB4C5E4),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Op(Goto, SpriteObject3BEvirFacingLeft),
        Frame(10),
        Frame(10),
        Frame(10),
        Frame(10),
        Op(Goto, SpriteObject3CEvirFacingRight));

    internal static int MechanicsWordCount => Layout.MechanicsWordCount;
    internal static int PresentationWordCount => Layout.PresentationSlotCount;
    internal static RoomSpriteObjectInstructionMechanicsWord MechanicsWord(int index)
    {
        (ushort address, ushort value) = Layout.MechanicsWord(index);
        return new(address, value);
    }
    internal static ushort PresentationWordAddress(int index) => Layout.PresentationSlotAddress(index);

    internal static ushort ReadMechanicsWord(ushort address) =>
        Layout.TryReadMechanicsWord(address, out ushort value) ? value :
            throw new InvalidDataException(
                $"Room sprite-object instruction mechanics pointer $B4:{address:X4} is not compiled.");

    internal static bool IsCompiledMechanicsByte(int address) => Layout.IsCompiledMechanicsByte(address);

    internal static bool TryGetPresentationWord(int address, out ushort wordAddress) =>
        Layout.TryGetPresentationWord(address, out wordAddress);
}
