using static SuperMetroid.Core.Game.InstructionItem;

namespace SuperMetroid.Core.Game;

internal abstract partial class TorizoInstructionProgramDefinitions
{
    /// <summary>BombLeft instruction items at $AA:B879..BC5F; native list names identify each group.</summary>
    private static InstructionItem[] BombLeftItems =>
    [
        Origin(0xb879),
        Entry(InstList_Torizo_BombTorizo_Initial_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedLeftWithRightFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetAnimationLock),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_WakeWhenBombTorizoChozoFinishesCrumbling),
        Op(CommonEnemyInstructionCodes.Sleep),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Frame(48),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(32),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(16),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(8),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(32),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0002),
        Entry(InstList_Torizo_BombTorizo_Initial_1),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_BombTorizo_Initial_1),
        Frame(48),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0000),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0002),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0004),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0006),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0008),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x000a),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetupPaletteTransitionToNormalTorizo),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0010),
        Entry(InstList_Torizo_BombTorizo_Initial_2),
        Frame(4),
        Op(TorizoInstructionCodes.Instruction_Torizo_AdvanceGradualColorChange),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_BombTorizo_Initial_2, TorizoInstructionCodes.RTL_AAC2C8),
        Op(TorizoInstructionCodes.Instruction_Torizo_ClearAnimationLock),
        Op(TorizoInstructionCodes.Instruction_Torizo_StartFightMusic_BombTorizoBellyPaletteFX),
        Frame(16),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Walking_LeftLegMoving),
        Origin(0xb962),
        Entry(InstList_Torizo_FacingLeft_TurningLeft),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(24),
        Entry(InstList_Torizo_FacingLeft_Walking_RightLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedLeftWithLeftFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(10),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingLeft_ExplosiveSwipe_LeftFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0002),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0004),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0006),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0008),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x000a),
        Entry(InstList_Torizo_FacingLeft_Walking_LeftLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedLeftWithRightFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(10),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingLeft_ExplosiveSwipe_RightFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x000c),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x000e),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0010),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0012),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0000),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Walking_RightLegMoving),
        Entry(InstList_Torizo_FacingLeft_SpewingChozoOrbs_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(16),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0003),
        Entry(InstList_Torizo_FacingLeft_SpewingChozoOrbs_RightFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizosChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0010),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingLeft_SpewingChozoOrbs_RightFootFwd_1),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(72),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingLeft_SpewingChozoOrbs_LeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(16),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0003),
        Entry(InstList_Torizo_FacingLeft_SpewingChozoOrbs_LeftFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizosChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0010),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingLeft_SpewingChozoOrbs_LeftFootFwd_1),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(72),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingLeft_SonicBooms_RightFootForward_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_Torizo_FacingLeft_SonicBooms_RightFootForward_1),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0000),
        Frame(2),
        Frame(24),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0001),
        Frame(2),
        Frame(56),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingLeft_SonicBooms_RightFootForward_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingLeft_SonicBooms_LeftFootForward_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_Torizo_FacingLeft_SonicBooms_LeftFootForward_1),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0000),
        Frame(2),
        Frame(24),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0001),
        Frame(2),
        Frame(56),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingLeft_SonicBooms_LeftFootForward_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingLeft_ExplosiveSwipe_RightFootForward),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0000),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0002),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0004),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0006),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0008),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000a),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000c),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000e),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0010),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0012),
        Frame(1),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingLeft_ExplosiveSwipe_LeftFootForward),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0000),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0002),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0004),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0006),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0008),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000a),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000c),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000e),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0010),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0012),
        Frame(1),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
    ];
}
