using static SuperMetroid.Core.Game.InstructionItem;

namespace SuperMetroid.Core.Game;

internal abstract partial class TorizoInstructionProgramDefinitions
{
    /// <summary>BombRight instruction items at $AA:BC60..C209; native list names identify each group.</summary>
    private static InstructionItem[] BombRightItems =>
    [
        Origin(0xbc60),
        Entry(InstList_Torizo_FacingLeft_JumpingForwards_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingLeft_Falling_0),
        Frame(5),
        Frame(5),
        Entry(InstList_Torizo_FacingLeft_JumpingForwards_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfRising, InstList_Torizo_FacingLeft_JumpingForwards_1),
        Entry(InstList_Torizo_FacingLeft_Falling_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingLeft_Falling_2),
        Entry(InstList_Torizo_FacingLeft_Falling_1),
        Frame(5),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Falling_1),
        Entry(InstList_Torizo_FacingLeft_Falling_2),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnTorizoLandingDustClouds),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfFaceBlownUp_ElseGotoY2_IfGolden, InstList_Torizo_FacingLeft_Faceless_Walking_LeftLegMoving, InstList_GoldenTorizo_WalkingLeft_LeftLegMoving),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Walking_LeftLegMoving),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_2),
        Frame(5),
        Frame(5),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfRising, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_1),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_2),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_4),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_3),
        Frame(5),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_3),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_4),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnTorizoLandingDustClouds),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfFaceBlownUp_ElseGotoY2_IfGolden, InstList_Torizo_FacingLeft_Faceless_Walking_RightLegMoving, InstList_GT_LandedFromBackwardsJump_FacingLeft_LeftFootFwd),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallY_OrY2_ForBombTorizoAttack, InstList_Torizo_FacingLeft_SpewingChozoOrbs_LeftFootFwd_0, InstList_Torizo_FacingLeft_SonicBooms_LeftFootForward_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Walking_RightLegMoving),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_2),
        Frame(5),
        Frame(5),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfRising, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_1),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_2),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_4),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_3),
        Frame(5),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_3),
        Entry(InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_4),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnTorizoLandingDustClouds),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfFaceBlownUp_ElseGotoY2_IfGolden, InstList_Torizo_FacingLeft_Faceless_Walking_LeftLegMoving, InstList_GT_LandedFromBackwardsJump_FacingLeft_RightFootFwd),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallY_OrY2_ForBombTorizoAttack, InstList_Torizo_FacingLeft_SpewingChozoOrbs_RightFootFwd_0, InstList_Torizo_FacingLeft_SonicBooms_RightFootForward_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Walking_LeftLegMoving),
        Entry(InstList_Torizo_FacingLeft_Faceless_TurningLeft),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(8),
        Entry(InstList_Torizo_FacingLeft_Faceless_Walking_RightLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedLeftWithLeftFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingLeft_ExplosiveSwipe_LeftFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0002),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0004),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0006),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0008),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x000a),
        Entry(InstList_Torizo_FacingLeft_Faceless_Walking_LeftLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedLeftWithRightFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingLeft_ExplosiveSwipe_RightFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x000c),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x000e),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0010),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0012),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0000),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingLeft_Faceless_Walking_RightLegMoving),
        Entry(UNUSED_InstList_Torizo_FacingRight_StandUp_AABD90),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedRightWithLeftFootState),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_WakeWhenBombTorizoChozoFinishesCrumbling),
        Op(CommonEnemyInstructionCodes.Sleep),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Frame(32),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0010),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0012),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0014),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0016),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0018),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x001a),
        Frame(8),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Walking_RightLegMoving),
        Entry(InstList_Torizo_FacingRight_TurningRight),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(24),
        Entry(InstList_Torizo_FacingRight_Walking_LeftLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedRightWithRightFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(10),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingRight_ExplosiveSwipe_RightFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0016),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0018),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x001a),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x001c),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x001e),
        Entry(InstList_Torizo_FacingRight_Walking_RightLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedRightWithLeftFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(10),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingRight_ExplosiveSwipe_LeftFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0020),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0022),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0024),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoYAndJumpBackwardsIfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0026),
        Frame(6),
        Op(TorizoInstructionCodes.Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY, 0x0014),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Walking_LeftLegMoving),
        Entry(InstList_Torizo_FacingRight_SpewingChozoOrbs_LeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(16),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0003),
        Entry(InstList_Torizo_FacingRight_SpewingChozoOrbs_LeftFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizosChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0010),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingRight_SpewingChozoOrbs_LeftFootFwd_1),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(72),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingRight_SpewingChozoOrbs_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(16),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0003),
        Entry(InstList_Torizo_FacingRight_SpewingChozoOrbs_RightFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizosChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0010),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingRight_SpewingChozoOrbs_RightFootFwd_1),
        Frame(8),
        Frame(8),
        Frame(8),
        Frame(72),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingRight_SonicBooms_LeftFootForward_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_Torizo_FacingRight_SonicBooms_LeftFootForward_1),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0000),
        Frame(2),
        Frame(24),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0001),
        Frame(2),
        Frame(56),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingRight_SonicBooms_LeftFootForward_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingRight_SonicBooms_RightFootForward_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_Torizo_FacingRight_SonicBooms_RightFootForward_1),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0000),
        Frame(2),
        Frame(24),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(6),
        Frame(2),
        Frame(2),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoSonicBoomWithParameterY, 0x0001),
        Frame(2),
        Frame(56),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_FacingRight_SonicBooms_RightFootForward_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingRight_ExplosiveSwipe_LeftFootForward),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0000),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0002),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0004),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0006),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0008),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000a),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000c),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000e),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0010),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0012),
        Frame(1),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingRight_ExplosiveSwipe_RightFootForward),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Attacking),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0000),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0002),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0004),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0006),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0008),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000a),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000c),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x000e),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0010),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnBombTorizoExplosiveSwipeWithParamY, 0x0012),
        Frame(1),
        Frame(16),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_Torizo_FacingRight_JumpingForwards_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingRight_Falling_0),
        Frame(5),
        Frame(5),
        Entry(InstList_Torizo_FacingRight_JumpingForwards_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfRising, InstList_Torizo_FacingRight_JumpingForwards_1),
        Entry(InstList_Torizo_FacingRight_Falling_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingRight_Falling_2),
        Entry(InstList_Torizo_FacingRight_Falling_1),
        Frame(5),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Falling_1),
        Entry(InstList_Torizo_FacingRight_Falling_2),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnTorizoLandingDustClouds),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfFaceBlownUp_ElseGotoY2_IfGolden, InstList_Torizo_FacingRight_Faceless_Walking_RightLegMoving, InstList_GoldenTorizo_WalkingRight_RightLegMoving),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Walking_RightLegMoving),
        Entry(InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_2),
        Frame(5),
        Frame(5),
        Entry(InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfRising, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_1),
        Entry(InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_2),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_4),
        Entry(InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_3),
        Frame(5),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_3),
        Entry(InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_4),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnTorizoLandingDustClouds),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfFaceBlownUp_ElseGotoY2_IfGolden, InstList_Torizo_FacingRight_Faceless_Walking_LeftLegMoving, InstList_GT_LandedFromBackwardsJump_FacingRight_RightFootFwd),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallY_OrY2_ForBombTorizoAttack, InstList_Torizo_FacingRight_SpewingChozoOrbs_RightFootFwd_0, InstList_Torizo_FacingRight_SonicBooms_RightFootForward_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Walking_LeftLegMoving),
        Entry(InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_2),
        Frame(5),
        Frame(5),
        Entry(InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfRising, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_1),
        Entry(InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_2),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Jumping_Falling),
        Op(TorizoInstructionCodes.Instruction_Torizo_LinkInstructionInY, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_4),
        Entry(InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_3),
        Frame(5),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_3),
        Entry(InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_4),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnTorizoLandingDustClouds),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfFaceBlownUp_ElseGotoY2_IfGolden, InstList_Torizo_FacingRight_Faceless_Walking_RightLegMoving, InstList_GT_LandedFromBackwardsJump_FacingRight_LeftFootFwd),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallY_OrY2_ForBombTorizoAttack, InstList_Torizo_FacingRight_SpewingChozoOrbs_LeftFootFwd_0, InstList_Torizo_FacingRight_SonicBooms_LeftFootForward_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Walking_RightLegMoving),
        Entry(InstList_Torizo_FacingRight_Faceless_TurningRight),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(8),
        Entry(InstList_Torizo_FacingRight_Faceless_Walking_LeftLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedRightWithRightFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingRight_ExplosiveSwipe_RightFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0016),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0018),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x001a),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x001c),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x001e),
        Entry(InstList_Torizo_FacingRight_Faceless_Walking_RightLegMoving),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedRightWithLeftFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_Torizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnLowHealthInitialDroolIfHealthIsLow),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_CallYIfSamusIsLessThan38PixelsInFront, InstList_Torizo_FacingRight_ExplosiveSwipe_LeftFootForward),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0020),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0022),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0024),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0026),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY, 0x0014),
        Op(CommonEnemyInstructionCodes.Goto, InstList_Torizo_FacingRight_Faceless_Walking_LeftLegMoving),
    ];
}
