using static SuperMetroid.Core.Game.InstructionItem;

namespace SuperMetroid.Core.Game;

internal abstract partial class TorizoInstructionProgramDefinitions
{
    /// <summary>GoldenRight instruction items at $AA:CDE1..D368; native list names identify each group.</summary>
    private static InstructionItem[] GoldenRightItems =>
    [
        Origin(0xcde1),
        Entry(InstList_GoldenTorizo_CaughtSuper_FacingLeft_LeftLegFwd),
        Op((ushort)TorizoInstruction.Instruction_Torizo_QueueSonicBoomSFX),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_SimpleMovement),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_SpawnSuperMissile),
        Frame(48),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(16),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_ClearCaughtSuperMissileFlag),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_RightLegMoving),
        Entry(InstList_GoldenTorizo_CaughtSuper_FacingLeft_RightLegFwd),
        Op((ushort)TorizoInstruction.Instruction_Torizo_QueueSonicBoomSFX),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_SimpleMovement),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_SpawnSuperMissile),
        Frame(48),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(16),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_ClearCaughtSuperMissileFlag),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_LeftLegMoving),
        Entry(InstList_GoldenTorizo_CaughtSuper_FacingRight_RightLegFwd),
        Op((ushort)TorizoInstruction.Instruction_Torizo_QueueSonicBoomSFX),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_SimpleMovement),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(2),
        Frame(2),
        Frame(2),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_SpawnSuperMissile),
        Frame(48),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(16),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_ClearCaughtSuperMissileFlag),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_LeftLegMoving),
        Entry(InstList_GoldenTorizo_CaughtSuper_FacingRight_LeftLegFwd),
        Op((ushort)TorizoInstruction.Instruction_Torizo_QueueSonicBoomSFX),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_SimpleMovement),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(1),
        Frame(2),
        Frame(2),
        Frame(2),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_SpawnSuperMissile),
        Frame(48),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(2),
        Frame(16),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_ClearCaughtSuperMissileFlag),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_RightLegMoving),
        Entry(InstList_GoldenTorizo_SitDownAttack_FacingLeft),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x000a),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0008),
        Frame(6),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0006),
        Frame(6),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0004),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0002),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0000),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0000),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0002),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0004),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0006),
        Frame(10),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0008),
        Frame(10),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x000a),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_LeftLegMoving),
        Entry(InstList_GoldenTorizo_SitDownAttack_FacingRight),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x001a),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0018),
        Frame(6),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0016),
        Frame(6),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0014),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0012),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0010),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0010),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0012),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0014),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0016),
        Frame(10),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0018),
        Frame(10),
        Op((ushort)TorizoInstruction.Instruction_Torizo_StandingUpMovement_IndexInY, 0x001a),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_RightLegMoving),
        Entry(InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_0),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0010),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0006),
        Entry(InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_1),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_QueueEggReleasedSFX),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_SpawnGoldenTorizoEgg),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_1),
        Entry(InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_2),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0001),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_EyeBeamAttack_0, InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_2),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_Return),
        Origin(0xd10d),
        Entry(InstList_GoldenTorizo_EyeBeamAttack_0),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_SimpleMovement),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_DisableEyeBeamExplosions),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_QueueLaserSFX),
        Entry(InstList_GoldenTorizo_EyeBeamAttack_1),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_SpawnEyeBeam, 0x0000),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0004),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_EyeBeamAttack_1),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0002),
        Entry(InstList_GoldenTorizo_EyeBeamAttack_2),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_EyeBeamAttack_2),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_EnableEyeBeamExplosions),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0008),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_DisableEyeBeamExplosions),
        Op((ushort)TorizoInstruction.Instruction_Torizo_ClearAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_Return),
        Origin(0xd193),
        Entry(InstList_Torizo_Stunned_0),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0018),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0002),
        Entry(InstList_Torizo_Stunned_1),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0003),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_Stunned_1),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0010),
        Op((ushort)TorizoInstruction.Instruction_Torizo_ClearAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_UnmarkStunned),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_Return),
        Skip(10),
        Entry(InstList_GoldenTorizo_Dodge_TurningLeft),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(24),
        Op((ushort)TorizoInstruction.Instruction_Torizo_ClearAnimationLock),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_RightLegMoving),
        Entry(InstList_GoldenTorizo_TurningLeft),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(8),
        Entry(InstList_GoldenTorizo_WalkingLeft_RightLegMoving),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetSteppedLeftWithLeftFootState),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpForwards_IfAtLeast70Pixel, InstList_Torizo_FacingLeft_JumpingForwards_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_IfStunHealthGreaterThan2A31, InstList_Torizo_Stunned_0),
        Op((ushort)TorizoInstruction.Instruction_GT_CallY_25Chance_IfSamusMorphedInFrontOfTorizo, InstList_GoldenTorizo_EyeBeamAttack_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0002),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0004),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_25Chance_IfHealthLessThan789, InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_LandLeftFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0006),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0008),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x000a),
        Entry(InstList_GoldenTorizo_WalkingLeft_LeftLegMoving),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetSteppedLeftWithRightFootState),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_IfSamusIsMorphedBehindTorizo, InstList_GoldenTorizo_SitDownAttack_FacingLeft),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpForwards_IfAtLeast70Pixel, InstList_Torizo_FacingLeft_JumpingForwards_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_IfStunHealthGreaterThan2A31, InstList_Torizo_Stunned_0),
        Op((ushort)TorizoInstruction.Instruction_GT_CallY_25Chance_IfSamusMorphedInFrontOfTorizo, InstList_GoldenTorizo_EyeBeamAttack_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x000c),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x000e),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_25Chance_IfHealthLessThan789, InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingLeft_JumpingBackward_RightFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0010),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0012),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0000),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_RightLegMoving),
        Entry(InstList_GoldenTorizo_Dodge_TurningRight),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(24),
        Op((ushort)TorizoInstruction.Instruction_Torizo_ClearAnimationLock),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_LeftLegMoving),
        Entry(InstList_GoldenTorizo_TurningRight),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetTorizoTurningAroundFlag),
        Frame(8),
        Entry(InstList_GoldenTorizo_WalkingRight_LeftLegMoving),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetSteppedRightWithRightFootState),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpForwards_IfAtLeast70Pixel, InstList_Torizo_FacingRight_JumpingForwards_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_IfStunHealthGreaterThan2A31, InstList_Torizo_Stunned_0),
        Op((ushort)TorizoInstruction.Instruction_GT_CallY_25Chance_IfSamusMorphedInFrontOfTorizo, InstList_GoldenTorizo_EyeBeamAttack_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0016),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0018),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_25Chance_IfHealthLessThan789, InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x001a),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackward_LandRightFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x001c),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x001e),
        Entry(InstList_GoldenTorizo_WalkingRight_RightLegMoving),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetSteppedRightWithLeftFootState),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op((ushort)TorizoInstruction.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(8),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_IfSamusIsMorphedBehindTorizo, InstList_GoldenTorizo_SitDownAttack_FacingRight),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpForwards_IfAtLeast70Pixel, InstList_Torizo_FacingRight_JumpingForwards_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_IfStunHealthGreaterThan2A31, InstList_Torizo_Stunned_0),
        Op((ushort)TorizoInstruction.Instruction_GT_CallY_25Chance_IfSamusMorphedInFrontOfTorizo, InstList_GoldenTorizo_EyeBeamAttack_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0020),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0022),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_CallY_25Chance_IfHealthLessThan789, InstList_GoldenTorizo_ReleaseGoldenTorizoEggs_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_GotoY_JumpBack_IfLessThan20Pixels, InstList_Torizo_FacingRight_JumpBackwards_LandLeftFootFwd_0),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0024),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0026),
        Frame(4),
        Op((ushort)TorizoInstruction.Instruction_GoldenTorizo_WalkingMovement_IndexInY, 0x0014),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_LeftLegMoving),
    ];
}
