using static SuperMetroid.Core.Game.InstructionItem;

namespace SuperMetroid.Core.Game;

internal abstract partial class TorizoInstructionProgramDefinitions
{
    /// <summary>Shared instruction items at $AA:B0E5..B223; native list names identify each group.</summary>
    private static InstructionItem[] SharedItems =>
    [
        Origin(0xb0e5),
        Entry(InstList_Torizo_SpecialCallable_BlowUpBombTorizosGut),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, RTS_AAC6AB),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_Spawn5LowHealthExplosion_SleepFor28Frames, 0x0000),
        Op((ushort)TorizoInstruction.Instruction_Torizo_MarkBTGutBlownUp_Spawn6BTDroolProjectiles),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_ClearAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_GotoGutExplosionLinkInstruction),
        Origin(0xb155),
        Entry(InstList_Torizo_Callable_BlowUpBombTorizosFace),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, RTS_AAC6AB),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_Spawn5LowHealthExplosion_SleepFor28Frames, 0x0006),
        Op((ushort)TorizoInstruction.Instruction_Torizo_MarkBombTorizoFaceBlownUp),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0001),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, Function_Torizo_NormalMovement),
        Op((ushort)TorizoInstruction.Instruction_Torizo_ClearAnimationLock),
        Op((ushort)TorizoInstruction.Instruction_Torizo_Return),
        Skip(10),
        Entry(InstList_Torizo_DeathSequence_0),
        Op((ushort)TorizoInstruction.Instruction_Torizo_FunctionInY, RTS_AAC6AB),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAnimationLock),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0008),
        Entry(InstList_Torizo_DeathSequence_1),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SpawnTorizoDeathExplosion_SleepFor1IFrame),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0006),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_DeathSequence_1),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetupPaletteTransitionToBlack),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x000e),
        Entry(InstList_Torizo_DeathSequence_2),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SpawnTorizoDeathExplosion_SleepFor1IFrame),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsVisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsInvisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SpawnTorizoDeathExplosion_SleepFor1IFrame),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsVisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsInvisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsVisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsInvisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsVisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetAsInvisible),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0002),
        Op((ushort)TorizoInstruction.Instruction_Torizo_AdvanceGradualColorChange),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_Torizo_DeathSequence_2),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0040),
        Op((ushort)TorizoInstruction.Instruction_Torizo_SetBossBit_QueueElevatorMusic_SpawnDrops),
        Op(CommonEnemyInstructionCodes.StopScript),
    ];
}
