using static SuperMetroid.Core.Game.InstructionItem;

namespace SuperMetroid.Core.Game;

internal static partial class TorizoInstructionProgramDefinitions
{
    /// <summary>GoldenLeft instruction items at $AA:C9CB..CDD6; native list names identify each group.</summary>
    private static InstructionItem[] GoldenLeftItems =>
    [
        Origin(0xc9cb),
        Entry(InstList_GoldenTorizo_Initial_0),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetSteppedLeftWithRightFootState),
        Op(TorizoInstructionCodes.Instruction_Torizo_SetAnimationLock),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_GoldenTorizo_WakeIfSamusIsBelowAndRightOfTargetPos),
        Frame(1),
        Op(CommonEnemyInstructionCodes.Sleep),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, Function_Torizo_SimpleMovement),
        Entry(InstList_GoldenTorizo_Initial_1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_GotoY_IfNotHitGround, InstList_GoldenTorizo_Initial_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayTorizoFootstepsSFX),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0004),
        Frame(4),
        Op(TorizoInstructionCodes.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0002),
        Frame(5),
        Op(TorizoInstructionCodes.Instruction_Torizo_SittingDownMovement_IndexInY, 0x0000),
        Op(TorizoInstructionCodes.Instruction_Torizo_FunctionInY, RTS_AAC6AB),
        Frame(48),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(32),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(16),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(8),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(32),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0002),
        Entry(InstList_GoldenTorizo_Initial_2),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Frame(4),
        Op(CommonEnemyInstructionCodes.CopyToVram),
        Skip(7),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_Initial_2),
        Frame(32),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0000),
        Frame(12),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0002),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0004),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0006),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x0008),
        Frame(8),
        Op(TorizoInstructionCodes.Instruction_Torizo_StandingUpMovement_IndexInY, 0x000a),
        Op(TorizoInstructionCodes.Instruction_Torizo_LoadGoldenTorizoPalettes),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0010),
        Entry(InstList_GoldenTorizo_Initial_3),
        Frame(4),
        Op(TorizoInstructionCodes.Instruction_Torizo_AdvanceGradualColorChange),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_Initial_3, TorizoInstructionCodes.RTL_AAC2C8),
        Op(TorizoInstructionCodes.Instruction_Torizo_ClearAnimationLock, TorizoInstructionCodes.Inst_Torizo_StartFightMusic_GoldenTorizoBellyPaletteFX),
        Frame(16),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_LeftLegMoving),
        Origin(0xcaff),
        Entry(InstList_GoldenTorizo_SpewChozoOrbs_FaceLeft_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Frame(6),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(6),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0006),
        Entry(InstList_GoldenTorizo_SpewChozoOrbs_FaceLeft_RightFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_SpawnChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0006),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SpewChozoOrbs_FaceLeft_RightFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SpewChozoOrbs_FacingLeft_LeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Frame(6),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(6),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0006),
        Entry(InstList_GoldenTorizo_SpewChozoOrbs_FacingLeft_LeftFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_SpawnChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0006),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SpewChozoOrbs_FacingLeft_LeftFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingLeft_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingLeft_RightFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0000),
        Frame(1),
        Frame(4),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0001),
        Frame(1),
        Frame(4),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SonicBooms_FacingLeft_RightFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingLeft_LeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingLeft_LeftFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0000),
        Frame(1),
        Frame(4),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0001),
        Frame(1),
        Frame(4),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SonicBooms_FacingLeft_LeftFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_LeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Frame(6),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(6),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0006),
        Entry(InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_LeftFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_SpawnChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0006),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_LeftFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Frame(6),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(6),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0006),
        Entry(InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_RightFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_Torizo_PlayShotTorizoSFX),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_SpawnChozoOrbs),
        Op(CommonEnemyInstructionCodes.WaitFrames, 0x0006),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_RightFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingRight_LeftFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingRight_LeftFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0000),
        Frame(1),
        Frame(4),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0001),
        Frame(1),
        Frame(4),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SonicBooms_FacingRight_LeftFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingRight_RightFootFwd_0),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Attacking),
        Op(CommonEnemyInstructionCodes.SetTimer, 0x0004),
        Entry(InstList_GoldenTorizo_SonicBooms_FacingRight_RightFootFwd_1),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0000),
        Frame(1),
        Frame(4),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(3),
        Frame(1),
        Frame(1),
        Op(TorizoInstructionCodes.Instruction_Torizo_SpawnGoldenTorizoSonicBoomWithParameterY, 0x0001),
        Frame(1),
        Frame(4),
        Op(CommonEnemyInstructionCodes.DecrementTimerAndGotoDuplicate, InstList_GoldenTorizo_SonicBooms_FacingRight_RightFootFwd_1),
        Op(TorizoInstructionCodes.Instruction_CommonAA_Enemy0FB2_InY, Function_GoldenTorizo_Movement_Walking),
        Op(TorizoInstructionCodes.Instruction_Torizo_Return),
        Entry(InstList_GT_LandedFromBackwardsJump_FacingLeft_LeftFootFwd),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_CallY_OrY2_ForAttack, InstList_GoldenTorizo_SpewChozoOrbs_FacingLeft_LeftFootFwd_0, InstList_GoldenTorizo_SonicBooms_FacingLeft_LeftFootFwd_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_RightLegMoving),
        Entry(InstList_GT_LandedFromBackwardsJump_FacingLeft_RightFootFwd),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_CallY_OrY2_ForAttack, InstList_GoldenTorizo_SpewChozoOrbs_FaceLeft_RightFootFwd_0, InstList_GoldenTorizo_SonicBooms_FacingLeft_RightFootFwd_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingLeft_LeftLegMoving),
        Entry(InstList_GT_LandedFromBackwardsJump_FacingRight_RightFootFwd),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_CallY_OrY2_ForAttack, InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_RightFootFwd_0, InstList_GoldenTorizo_SonicBooms_FacingRight_RightFootFwd_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_LeftLegMoving),
        Entry(InstList_GT_LandedFromBackwardsJump_FacingRight_LeftFootFwd),
        Op(TorizoInstructionCodes.Instruction_GoldenTorizo_CallY_OrY2_ForAttack, InstList_GoldenTorizo_SpewChozoOrb_FacingLeft_LeftFootFwd_0, InstList_GoldenTorizo_SonicBooms_FacingRight_LeftFootFwd_0),
        Op(CommonEnemyInstructionCodes.Goto, InstList_GoldenTorizo_WalkingRight_RightLegMoving),
        Skip(10),
    ];
}
