<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SuperMetroid.Desktop/SuperMetroid.Desktop.csproj" />
    <Compile Include="../SuperMetroid.RenderVerification/NativeConsoleErrors.cs" Link="NativeConsoleErrors.cs" />
  </ItemGroup>
</Project>
