using System.Security.Cryptography;
using System.Text.Json;

namespace SuperMetroid.Core.Audio;

/// <summary>
/// Build-stage extractor for the game's exact SPC upload streams and their inspectable
/// derivatives. The lossless <c>.spcu</c> files retain sequence and instrument data while a
/// deduplicated, stable-ID WAV catalog supplies every runtime sample. This deliberately makes
/// replacing a stock waveform independent from the managed sequencer and mixer.
/// </summary>
public static class SpcAudioAssetExtractor
{
    private const int MaximumTrackPointerCount = 32;
    private const int InstrumentTableByteLength = 0x100;
    private const int BrrDirectoryAddress = 0x6d00;
    private const int BrrDirectoryEntrySize = 4;
    private const int BrrBlockByteLength = 9;
    private const int MaximumBrrBlocks = ushort.MaxValue / BrrBlockByteLength;

    /// <summary>Extracts all required assets from the repository's private raw directory.</summary>
    public static AudioAssetManifest Extract(string rawDirectory, string audioDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(rawDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(audioDirectory);
        rawDirectory = Path.GetFullPath(rawDirectory);
        audioDirectory = Path.GetFullPath(audioDirectory);
        if (!Directory.Exists(rawDirectory))
            throw new DirectoryNotFoundException($"Raw asset directory '{rawDirectory}' does not exist.");

        string streamsDirectory = Path.Combine(audioDirectory, "streams");
        string samplesDirectory = Path.Combine(audioDirectory, "samples");
        Directory.CreateDirectory(streamsDirectory);
        // This directory is wholly generated by this extractor. Rebuilding it atomically at
        // the directory level prevents obsolete per-bank WAVs from masquerading as live assets.
        if (Directory.Exists(samplesDirectory))
            Directory.Delete(samplesDirectory, recursive: true);
        Directory.CreateDirectory(samplesDirectory);

        List<AudioUploadManifestEntry> uploads = [];
        Dictionary<int, byte[]> sourceStreams = [];
        foreach (AudioUploadAssetDefinition definition in AudioAssetCatalogData.All)
        {
            string sourcePath = Path.Combine(rawDirectory, definition.Name + ".bin");
            if (!File.Exists(sourcePath))
                throw new FileNotFoundException($"Required raw audio stream '{sourcePath}' is missing.", sourcePath);
            byte[] stream = File.ReadAllBytes(sourcePath);
            ValidateUploadStream(stream, definition.Name);
            string relativePath = Path.Combine("streams", $"{definition.DataIndex:X2}-{definition.Name}.spcu");
            File.WriteAllBytes(Path.Combine(audioDirectory, relativePath), stream);
            sourceStreams.Add(definition.SnesAddress, stream);
            uploads.Add(new AudioUploadManifestEntry(
                definition.Name,
                definition.SnesAddress,
                definition.DataIndex,
                relativePath.Replace('\\', '/'),
                stream.Length,
                Convert.ToHexString(SHA256.HashData(stream))));
        }

        byte[] commonRam = new byte[SpcDriverData.ApuRamSize];
        bool[] commonWritten = new bool[SpcDriverData.ApuRamSize];
        ApplyUpload(commonRam, commonWritten, sourceStreams[AudioAssetCatalogData.Common.SnesAddress]);

        var canonicalSamples = new CanonicalSampleBuilder(audioDirectory, samplesDirectory);
        List<AudioBankMetadata> banks =
        [
            ExtractBankMetadata(
                AudioAssetCatalogData.Common,
                commonRam,
                commonWritten,
                canonicalSamples,
                includeTrackPointers: false),
        ];
        foreach (AudioUploadAssetDefinition definition in AudioAssetCatalogData.Music)
        {
            byte[] ram = (byte[])commonRam.Clone();
            bool[] written = (bool[])commonWritten.Clone();
            ApplyUpload(ram, written, sourceStreams[definition.SnesAddress]);
            banks.Add(ExtractBankMetadata(
                definition,
                ram,
                written,
                canonicalSamples,
                includeTrackPointers: true));
        }

        AudioAssetManifest manifest = new(
            AudioAssetManifest.CurrentFormatVersion,
            uploads,
            canonicalSamples.Metadata,
            banks,
            ExtractSoundLibraries());
        File.WriteAllText(
            Path.Combine(audioDirectory, ExtractedAudioAssetCatalog.ManifestFileName),
            JsonSerializer.Serialize(manifest, AudioAssetJson.Options));
        return manifest;
    }

    private static AudioBankMetadata ExtractBankMetadata(
        AudioUploadAssetDefinition definition,
        byte[] ram,
        bool[] written,
        CanonicalSampleBuilder canonicalSamples,
        bool includeTrackPointers)
    {
        List<ushort> trackPointers = [];
        if (includeTrackPointers)
        {
            trackPointers.Add(ReadWord(ram, SpcDriverData.Ram.DefaultMusicPointer));
            for (int track = 1; track < MaximumTrackPointerCount; track++)
            {
                ushort pointer = ReadWord(ram, SpcDriverData.Ram.DefaultMusicPointer + track * 2);
                if (pointer == 0 || !written[pointer])
                    break;
                trackPointers.Add(pointer);
            }
        }

        List<AudioInstrumentMetadata> instruments = [];
        int instrumentCount = InstrumentTableByteLength / SpcDriverData.Ram.InstrumentRecordSize;
        for (int instrument = 0; instrument < instrumentCount; instrument++)
        {
            int address = SpcDriverData.Ram.InstrumentTable +
                instrument * SpcDriverData.Ram.InstrumentRecordSize;
            byte source = ram[address];
            instruments.Add(new AudioInstrumentMetadata(
                instrument,
                (source & 0x80) != 0,
                source,
                ram[address + 1],
                ram[address + 2],
                ram[address + 3],
                unchecked((ushort)((ram[address + 4] << 8) | ram[address + 5]))));
        }

        List<AudioSampleMetadata> samples = [];
        ushort firstSampleAddress = ReadWord(ram, BrrDirectoryAddress);
        int directoryBytes = firstSampleAddress - BrrDirectoryAddress;
        if (directoryBytes <= 0 || directoryBytes % BrrDirectoryEntrySize != 0 ||
            directoryBytes / BrrDirectoryEntrySize > byte.MaxValue + 1)
        {
            throw new InvalidDataException(
                $"{definition.Name} has invalid BRR directory boundary ${firstSampleAddress:X4}.");
        }
        int sourceCount = directoryBytes / BrrDirectoryEntrySize;
        for (int source = 0; source < sourceCount; source++)
        {
            int directory = BrrDirectoryAddress + source * BrrDirectoryEntrySize;
            ushort start = ReadWord(ram, directory);
            ushort loop = ReadWord(ram, directory + 2);
            if (start == 0 || !written[start])
                continue;
            if (!TryDecodeBrr(ram, written, start, loop, out short[] pcm, out int blocks, out int? loopSample))
                continue;

            string sampleId = canonicalSamples.Add(
                definition.DataIndex,
                unchecked((byte)source),
                pcm,
                loopSample);
            samples.Add(new AudioSampleMetadata(
                unchecked((byte)source), start, loop, blocks, sampleId));
        }

        return new AudioBankMetadata(
            definition.Name,
            definition.DataIndex,
            definition.SnesAddress,
            trackPointers,
            instruments,
            samples);
    }

    private static List<AudioSoundLibraryMetadata> ExtractSoundLibraries()
    {
        List<AudioSoundLibraryMetadata> libraries = [];
        for (int library = 0; library < SpcSoundEffectTables.StreamPointerTables.Length; library++)
        {
            ushort[] pointers = SpcSoundEffectTables.StreamPointerTables[library];
            byte[] configurations = SpcSoundEffectTables.Configurations[library];
            List<AudioSoundEffectMetadata> effects = [];
            for (int index = 0; index < pointers.Length; index++)
            {
                effects.Add(new AudioSoundEffectMetadata(
                    unchecked((byte)(index + 1)), pointers[index], configurations[index]));
            }
            libraries.Add(new AudioSoundLibraryMetadata(library + 1, effects));
        }
        return libraries;
    }

    /// <summary>Builds an exact finite PCM prefix and recurring loop from BRR predictor states.</summary>
    internal static bool TryDecodeBrr(
        byte[] ram,
        bool[] written,
        ushort start,
        ushort loop,
        out short[] pcm,
        out int blockCount,
        out int? loopSampleIndex)
    {
        List<short> samples = [];
        HashSet<ushort> blockAddresses = [];
        Dictionary<(int Old, int Older), int> loopHistories = [];
        int address = start;
        int old = 0;
        int older = 0;
        bool followingLoop = false;
        blockCount = 0;
        while (samples.Count < BrrExtractionLimits.MaximumDecodedLoopSamples)
        {
            if (!followingLoop && blockCount >= MaximumBrrBlocks)
                break;
            if (address > ushort.MaxValue - BrrBlockByteLength)
                break;
            for (int index = 0; index < BrrBlockByteLength; index++)
            {
                if (!written[address + index])
                    goto Invalid;
            }

            blockAddresses.Add(unchecked((ushort)address));
            byte header = ram[address];
            int shift = header >> 4;
            int filter = (header >> 2) & 3;
            if (address == loop)
            {
                // A loop is repeatable only when it returns to the same predictor
                // history, not merely the same BRR address. Filter zero discards both
                // history words, so its entry state can be normalized immediately.
                var history = filter == 0 ? (0, 0) : (old, older);
                if (followingLoop && loopHistories.TryGetValue(history, out int repeatAt))
                {
                    pcm = [.. samples];
                    loopSampleIndex = repeatAt;
                    return true;
                }
                loopHistories.TryAdd(history, samples.Count);
            }
            for (int sampleIndex = 0; sampleIndex < PcmSampleFormat.StreamingWindowSampleCount; sampleIndex++)
            {
                byte packed = ram[address + 1 + sampleIndex / 2];
                int sample = (sampleIndex & 1) == 0 ? packed >> 4 : packed & 0x0f;
                if (sample > 7)
                    sample -= 16;
                sample = shift <= 0x0c ? (sample << shift) >> 1 : (sample >> 3) << 12;
                sample += filter switch
                {
                    0 => 0,
                    1 => old + (-old >> 4),
                    2 => 2 * old + ((3 * -old) >> 5) - older + (older >> 4),
                    3 => 2 * old + ((13 * -old) >> 6) - older + ((3 * older) >> 4),
                    _ => throw new InvalidDataException($"Impossible BRR filter {filter}."),
                };
                sample = Math.Clamp(sample, short.MinValue, short.MaxValue);
                sample = unchecked((short)((sample & 0x7fff) << 1)) >> 1;
                older = old;
                old = sample;
                samples.Add(unchecked((short)sample));
            }
            address += BrrBlockByteLength;
            if (!followingLoop) blockCount++;
            if ((header & 1) != 0)
            {
                if ((header & 2) == 0)
                {
                    pcm = [.. samples];
                    loopSampleIndex = null;
                    return true;
                }
                if (!blockAddresses.Contains(loop)) goto Invalid;
                // Keep transient loop passes in the WAV prefix. Once the exact
                // history repeats, the remaining cycle is ordinary replaceable PCM;
                // the runtime needs neither a BRR decoder nor special loop effects.
                followingLoop = true;
                address = loop;
            }
        }

        if (followingLoop)
            throw new InvalidDataException(
                $"BRR sample ${start:X4} loop ${loop:X4} did not reach a repeated decoder state " +
                $"within {BrrExtractionLimits.MaximumDecodedLoopSamples} PCM frames.");

    Invalid:
        pcm = [];
        blockCount = 0;
        loopSampleIndex = null;
        return false;
    }

    private static void ValidateUploadStream(ReadOnlySpan<byte> stream, string name)
    {
        byte[] scratch = new byte[SpcDriverData.ApuRamSize];
        bool[] written = new bool[SpcDriverData.ApuRamSize];
        try
        {
            ApplyUpload(scratch, written, stream);
        }
        catch (InvalidDataException exception)
        {
            throw new InvalidDataException($"Raw audio asset '{name}' is not a valid SPC upload stream.", exception);
        }
    }

    private static void ApplyUpload(byte[] ram, bool[] written, ReadOnlySpan<byte> stream)
    {
        int offset = 0;
        for (;;)
        {
            if (offset > stream.Length - 2)
                throw new InvalidDataException("SPC upload ended before its terminating length word.");
            ushort length = unchecked((ushort)(stream[offset] | (stream[offset + 1] << 8)));
            offset += 2;
            if (length == 0)
            {
                // Retail assets retain the two-byte SPC execution address consumed by the
                // upload handshake after its zero-length marker. The managed driver already
                // runs, so playback ignores it while extraction preserves it byte-for-byte.
                if (stream.Length - offset is not 0 and not 2)
                    throw new InvalidDataException($"SPC upload has {stream.Length - offset} unexpected bytes after its terminator.");
                return;
            }
            if (offset > stream.Length - 2)
                throw new InvalidDataException("SPC upload ended before a destination word.");
            ushort destination = unchecked((ushort)(stream[offset] | (stream[offset + 1] << 8)));
            offset += 2;
            if (length > stream.Length - offset)
                throw new InvalidDataException($"SPC upload record ${destination:X4} overruns its source stream.");
            if (destination + length > ram.Length)
                throw new InvalidDataException($"SPC upload record ${destination:X4}+${length:X4} overruns APU RAM.");
            stream.Slice(offset, length).CopyTo(ram.AsSpan(destination, length));
            Array.Fill(written, true, destination, length);
            offset += length;
        }
    }

    private static ushort ReadWord(byte[] bytes, int address) =>
        unchecked((ushort)(bytes[address] | (bytes[address + 1] << 8)));

    /// <summary>
    /// Assigns the first cartridge occurrence of a unique waveform/loop pair a readable,
    /// durable identity. Content hashes are only deduplication and integrity mechanisms:
    /// replacing a WAV later does not force callers to rename its sample ID.
    /// </summary>
    private sealed class CanonicalSampleBuilder
    {
        private readonly string audioDirectory;
        private readonly string samplesDirectory;
        private readonly Dictionary<string, string> idsByContent = new(StringComparer.Ordinal);
        private readonly List<AudioCanonicalSampleMetadata> metadata = [];

        internal CanonicalSampleBuilder(string audioDirectory, string samplesDirectory)
        {
            this.audioDirectory = audioDirectory;
            this.samplesDirectory = samplesDirectory;
        }

        internal IReadOnlyList<AudioCanonicalSampleMetadata> Metadata => metadata;

        internal string Add(byte dataIndex, byte source, short[] pcm, int? loopSampleIndex)
        {
            byte[] pcmBytes = new byte[checked(pcm.Length * sizeof(short))];
            Buffer.BlockCopy(pcm, 0, pcmBytes, 0, pcmBytes.Length);
            string contentKey = $"{PcmSampleFormat.StockSampleRate}:{loopSampleIndex?.ToString() ?? "-"}:" +
                Convert.ToHexString(SHA256.HashData(pcmBytes));
            if (idsByContent.TryGetValue(contentKey, out string? existingId))
                return existingId;

            string id = $"sample-{dataIndex:X2}-{source:X2}".ToLowerInvariant();
            string absolutePath = Path.Combine(samplesDirectory, id + ".wav");
            PcmWaveFile.WriteMonoPcm16(absolutePath, PcmSampleFormat.StockSampleRate, pcm);
            byte[] waveBytes = File.ReadAllBytes(absolutePath);
            string relativePath = Path.GetRelativePath(audioDirectory, absolutePath).Replace('\\', '/');
            metadata.Add(new AudioCanonicalSampleMetadata(
                id,
                relativePath,
                PcmSampleFormat.StockSampleRate,
                pcm.Length,
                loopSampleIndex,
                Convert.ToHexString(SHA256.HashData(waveBytes))));
            idsByContent.Add(contentKey, id);
            return id;
        }
    }
}
