<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="[3.8.3]" />
    <ProjectReference Include="../SuperMetroid.Core/SuperMetroid.Core.csproj" />
    <Content Include="../../D3D11_THIRD_PARTY_NOTICES.txt" Link="D3D11_THIRD_PARTY_NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <Import Project="ShaderBuild.targets" />
</Project>
