using SuperMetroid.Core.Assets;
using SuperMetroid.Core.Game;

namespace SuperMetroid.Core.Rendering;

/// <summary>Replays the suit pickup's WH0/WH1 fixed-color window over a composed frame.</summary>
public static class SamusSuitPickupRenderer
{
    private const int Width = 256;
    private const int Height = 224;

    /// <summary>
    /// Applies `$91:D692`'s COLDATA addition inside the exact table generated by bank $88.
    /// </summary>
    /// <remarks>
    /// The hardware performs this while scanning the already-selected main-screen BG/OBJ
    /// pixels. Applying the same saturating five-bit addition after the desktop compositor
    /// is equivalent for this effect and avoids teaching every room renderer about a
    /// transient Samus-owned HDMA channel.
    /// </remarks>
    public static void Composite(Span<Rgba32> frame, SamusSuitPickupState pickup)
    {
        ArgumentNullException.ThrowIfNull(pickup);
        if (frame.Length != Width * Height)
            throw new ArgumentException("Suit-pickup compositor requires one 256x224 frame.", nameof(frame));
        if (!pickup.IsActive)
            return;

        byte red = ExpandFiveBit(pickup.FixedColorRed);
        byte green = ExpandFiveBit(pickup.FixedColorGreen);
        byte blue = ExpandFiveBit(pickup.FixedColorBlue);
        ReadOnlySpan<ushort> windows = pickup.WindowTable;
        for (int y = 0; y < Height; y++)
        {
            ushort endpoints = windows[y];
            int left = unchecked((byte)endpoints);
            int right = unchecked((byte)(endpoints >> 8));
            if (left > right)
                continue;

            int row = y * Width;
            for (int x = left; x <= right; x++)
            {
                Rgba32 source = frame[row + x];
                frame[row + x] = new Rgba32(
                    SaturatingAdd(source.R, red),
                    SaturatingAdd(source.G, green),
                    SaturatingAdd(source.B, blue),
                    source.A);
            }
        }
    }

    private static byte ExpandFiveBit(byte rawColdata) =>
        (byte)(((rawColdata & 0x1f) << 3) | ((rawColdata & 0x1f) >> 2));

    private static byte SaturatingAdd(byte left, byte right) =>
        unchecked((byte)Math.Min(byte.MaxValue, left + right));
}
