namespace SuperMetroid.Core.Frontend;

/// <summary>The ten bank-$8B reward gesture and jump cinematic-object definitions.</summary>
internal enum EndingRewardActor : ushort
{
    /// <summary>$8B:EF33, suitless upper hair-release actor spawned by E342.</summary>
    SuitlessUpper = 0xef33,
    /// <summary>$8B:EF39, suitless lower hair-release actor spawned by E342.</summary>
    SuitlessLower = 0xef39,
    /// <summary>$8B:EF3F, suitless jumping actor spawned by F51D.</summary>
    JumpSuitlessBody = 0xef3f,
    /// <summary>$8B:EF57, suited gesture body.</summary>
    SuitedBody = 0xef57,
    /// <summary>$8B:EF5D, suited moving thumbs-up arm.</summary>
    SuitedArm = 0xef5d,
    /// <summary>$8B:EF63, helmeted gesture head.</summary>
    HelmetedHead = 0xef63,
    /// <summary>$8B:EF69, helmetless gesture head.</summary>
    HelmetlessHead = 0xef69,
    /// <summary>$8B:EF6F, suited jump body spawned by F554.</summary>
    JumpSuitedBody = 0xef6f,
    /// <summary>$8B:EF75, helmeted jump head spawned by F554.</summary>
    JumpHelmetedHead = 0xef75,
    /// <summary>$8B:EF7B, helmetless jump head spawned by F554.</summary>
    JumpHelmetlessHead = 0xef7b,
}

/// <summary>The four bank-$8B reward actor initialization routines.</summary>
internal enum EndingRewardInitialization : ushort
{
    /// <summary>$8B:F143 initializes suitless actors at (120,136), OBJ palette five.</summary>
    Suitless = 0xf143,
    /// <summary>$8B:F156 initializes suited body/arm at (120,152), OBJ palette six.</summary>
    SuitedBody = 0xf156,
    /// <summary>$8B:F169 initializes the helmeted head at (124,108), OBJ palette six.</summary>
    HelmetedHead = 0xf169,
    /// <summary>$8B:F17C initializes the helmetless head at (121,107), OBJ palette five.</summary>
    HelmetlessHead = 0xf17c,
}

/// <summary>Bank-$8B reward gesture constructors and their jump handoffs.</summary>
internal static class EndingRewardActorDefinitions
{
    /// <summary>$8B:F51C, distinct RTS pre-instruction used by the suitless upper actor.</summary>
    public const ushort SuitlessUpperNoOp = 0xf51c;
    /// <summary>$8B:93D9, shared RTS pre-instruction used by the other reward actors.</summary>
    public const ushort SharedNoOp = 0x93d9;
    /// <summary>
    /// Resolves one complete native initialization/pre-instruction/list record. The
    /// selected animation lists are generated by EndingRewardInstructionDefinitions.
    /// </summary>
    public static EndingRewardActorDefinition Get(EndingRewardActor definition) => definition switch
    {
        EndingRewardActor.SuitlessUpper => new(EndingRewardInitialization.Suitless, SuitlessUpperNoOp, 0xed2d),
        EndingRewardActor.SuitlessLower => new(EndingRewardInitialization.Suitless, SharedNoOp, 0xed59),
        EndingRewardActor.SuitedBody => new(EndingRewardInitialization.SuitedBody, SharedNoOp, 0xedc9),
        EndingRewardActor.SuitedArm => new(EndingRewardInitialization.SuitedBody, SharedNoOp, 0xedd3),
        EndingRewardActor.HelmetedHead => new(EndingRewardInitialization.HelmetedHead, SharedNoOp, 0xee0f),
        EndingRewardActor.HelmetlessHead => new(EndingRewardInitialization.HelmetlessHead, SharedNoOp, 0xee15),
        EndingRewardActor.JumpSuitlessBody => new(EndingRewardInitialization.Suitless, SharedNoOp, 0xed7f),
        EndingRewardActor.JumpSuitedBody => new(EndingRewardInitialization.SuitedBody, SharedNoOp, 0xee27),
        EndingRewardActor.JumpHelmetedHead => new(EndingRewardInitialization.HelmetedHead, SharedNoOp, 0xee3d),
        EndingRewardActor.JumpHelmetlessHead => new(EndingRewardInitialization.HelmetlessHead, SharedNoOp, 0xee4d),
        _ => throw new InvalidOperationException($"Undefined {nameof(EndingRewardActor)} {(int)definition:X4}."),
    };

    /// <summary>Literal position/palette writes made by the four native reward initialization routines.</summary>
    public static (int X, int Y, int Palette) GetInitialization(EndingRewardInitialization address) => address switch
    {
        EndingRewardInitialization.Suitless => (120, 136, 0x0a00),
        EndingRewardInitialization.SuitedBody => (120, 152, 0x0c00),
        EndingRewardInitialization.HelmetedHead => (124, 108, 0x0c00),
        EndingRewardInitialization.HelmetlessHead => (121, 107, 0x0a00),
        _ => throw new InvalidOperationException($"Undefined {nameof(EndingRewardInitialization)} {(int)address:X4}."),
    };
}

/// <summary>One native six-byte ending reward cinematic-object definition.</summary>
internal readonly record struct EndingRewardActorDefinition(
    EndingRewardInitialization Initialization,
    ushort PreInstruction,
    ushort InstructionList);
