namespace SuperMetroid.Core.Frontend;

/// <summary>Compiled stock attract scene mechanics, joined from the pinned NTSC scene tables.</summary>
/// <remarks>
/// Equipment, placement, duration and setup identities are engine definitions, not
/// editable audiovisual assets. The cartridge reader remains a development oracle.
/// These records do not contain graphics, audio samples or a reconstructed ROM image.
/// </remarks>
public static class StockAttractDemoScenes
{
    private static readonly AttractDemoScene[][] Sets =
    [
        [
            // Set 0, scene 0: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x91f8,
                DoorPointer: 0x896a,
                DoorSlot: 1,
                CameraX: 1024,
                CameraY: 1024,
                SamusYFromTop: 64,
                SamusXFromCenter: 1,
                Duration: 1235,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.LandingSiteSky,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.LandingSite,
                Items: 0x0000,
                Missiles: 0,
                SuperMissiles: 0,
                PowerBombs: 0,
                Health: 99,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9e52),
            // Set 0, scene 1: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9f11,
                DoorPointer: 0x8eaa,
                DoorSlot: 1,
                CameraX: 0,
                CameraY: 0,
                SamusYFromTop: 107,
                SamusXFromCenter: -46,
                Duration: 337,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x0004,
                Missiles: 5,
                SuperMissiles: 0,
                PowerBombs: 0,
                Health: 99,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9e88),
            // Set 0, scene 2: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9d9c,
                DoorPointer: 0x8dc6,
                DoorSlot: 0,
                CameraX: 256,
                CameraY: 0,
                SamusYFromTop: 187,
                SamusXFromCenter: -32,
                Duration: 378,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x0004,
                Missiles: 15,
                SuperMissiles: 0,
                PowerBombs: 0,
                Health: 199,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9eac),
            // Set 0, scene 3: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xb106,
                DoorPointer: 0x970e,
                DoorSlot: 0,
                CameraX: 1792,
                CameraY: 0,
                SamusYFromTop: 139,
                SamusXFromCenter: 72,
                Duration: 420,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0x2105,
                Missiles: 30,
                SuperMissiles: 5,
                PowerBombs: 0,
                Health: 299,
                CollectedBeams: 0x1004,
                EquippedBeams: 0x1004,
                InputObject: 0x9e5e),
            // Set 0, scene 4: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xaffb,
                DoorPointer: 0x9792,
                DoorSlot: 1,
                CameraX: 0,
                CameraY: 0,
                SamusYFromTop: 139,
                SamusXFromCenter: -62,
                Duration: 444,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x6105,
                Missiles: 30,
                SuperMissiles: 5,
                PowerBombs: 5,
                Health: 399,
                CollectedBeams: 0x1006,
                EquippedBeams: 0x1006,
                InputObject: 0x9eb2),
            // Set 0, scene 5: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9d19,
                DoorPointer: 0x8e7a,
                DoorSlot: 0,
                CameraX: 512,
                CameraY: 1536,
                SamusYFromTop: 153,
                SamusXFromCenter: 39,
                Duration: 613,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.ChargeBeamScroll,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.MorphLeft,
                Items: 0x0004,
                Missiles: 20,
                SuperMissiles: 0,
                PowerBombs: 0,
                Health: 199,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9e58),
        ],
        [
            // Set 1, scene 0: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xa408,
                DoorPointer: 0xa36c,
                DoorSlot: 0,
                CameraX: 256,
                CameraY: 256,
                SamusYFromTop: 139,
                SamusXFromCenter: 86,
                Duration: 509,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0x2105,
                Missiles: 30,
                SuperMissiles: 5,
                PowerBombs: 0,
                Health: 299,
                CollectedBeams: 0x1006,
                EquippedBeams: 0x1006,
                InputObject: 0x9eb8),
            // Set 1, scene 1: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9c5e,
                DoorPointer: 0x8cca,
                DoorSlot: 3,
                CameraX: 512,
                CameraY: 0,
                SamusYFromTop: 139,
                SamusXFromCenter: 73,
                Duration: 410,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0x0004,
                Missiles: 10,
                SuperMissiles: 0,
                PowerBombs: 0,
                Health: 199,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9e94),
            // Set 1, scene 2: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9e52,
                DoorPointer: 0x8dea,
                DoorSlot: 3,
                CameraX: 1280,
                CameraY: 768,
                SamusYFromTop: 171,
                SamusXFromCenter: -30,
                Duration: 279,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x0004,
                Missiles: 25,
                SuperMissiles: 5,
                PowerBombs: 0,
                Health: 199,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9ea0),
            // Set 1, scene 3: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xaf14,
                DoorPointer: 0x967e,
                DoorSlot: 2,
                CameraX: 768,
                CameraY: 0,
                SamusYFromTop: 139,
                SamusXFromCenter: 75,
                Duration: 970,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0xe325,
                Missiles: 75,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 899,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9e76),
            // Set 1, scene 4: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9879,
                DoorPointer: 0x8982,
                DoorSlot: 3,
                CameraX: 0,
                CameraY: 0,
                SamusYFromTop: 187,
                SamusXFromCenter: -15,
                Duration: 213,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0xe32d,
                Missiles: 85,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 999,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9e9a),
            // Set 1, scene 5: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9cb3,
                DoorPointer: 0x8dd2,
                DoorSlot: 1,
                CameraX: 1024,
                CameraY: 512,
                SamusYFromTop: 128,
                SamusXFromCenter: 5,
                Duration: 791,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.FallingLeft,
                Items: 0xe105,
                Missiles: 45,
                SuperMissiles: 5,
                PowerBombs: 5,
                Health: 399,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9e64),
        ],
        [
            // Set 2, scene 0: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xcc6f,
                DoorPointer: 0xa21c,
                DoorSlot: 3,
                CameraX: 512,
                CameraY: 0,
                SamusYFromTop: 96,
                SamusXFromCenter: 4,
                Duration: 751,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0xe105,
                Missiles: 55,
                SuperMissiles: 5,
                PowerBombs: 5,
                Health: 399,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9e70),
            // Set 2, scene 1: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x91f8,
                DoorPointer: 0x896a,
                DoorSlot: 1,
                CameraX: 768,
                CameraY: 1024,
                SamusYFromTop: 176,
                SamusXFromCenter: 0,
                Duration: 199,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.LandingSiteSky,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.DiagonalShinespark,
                Items: 0xf33f,
                Missiles: 85,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 999,
                CollectedBeams: 0x100f,
                EquippedBeams: 0x1000,
                InputObject: 0x9e82),
            // Set 2, scene 2: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xa56b,
                DoorPointer: 0x919e,
                DoorSlot: 1,
                CameraX: 0,
                CameraY: 256,
                SamusYFromTop: 139,
                SamusXFromCenter: -46,
                Duration: 723,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x0104,
                Missiles: 25,
                SuperMissiles: 5,
                PowerBombs: 0,
                Health: 299,
                CollectedBeams: 0x1004,
                EquippedBeams: 0x1004,
                InputObject: 0x9e7c),
            // Set 2, scene 3: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xa322,
                DoorPointer: 0x90ea,
                DoorSlot: 0,
                CameraX: 0,
                CameraY: 1792,
                SamusYFromTop: 139,
                SamusXFromCenter: -86,
                Duration: 356,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x2105,
                Missiles: 30,
                SuperMissiles: 5,
                PowerBombs: 0,
                Health: 299,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9e6a),
            // Set 2, scene 4: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xa59f,
                DoorPointer: 0x91b6,
                DoorSlot: 1,
                CameraX: 0,
                CameraY: 256,
                SamusYFromTop: 139,
                SamusXFromCenter: -65,
                Duration: 319,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.KraidTimer,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x0104,
                Missiles: 25,
                SuperMissiles: 5,
                PowerBombs: 0,
                Health: 299,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9e8e),
            // Set 2, scene 5: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xa66a,
                DoorPointer: 0x91f2,
                DoorSlot: 1,
                CameraX: 0,
                CameraY: 0,
                SamusYFromTop: 139,
                SamusXFromCenter: -79,
                Duration: 407,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.DefeatedKraid,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0x2105,
                Missiles: 30,
                SuperMissiles: 5,
                PowerBombs: 5,
                Health: 299,
                CollectedBeams: 0x1008,
                EquippedBeams: 0x1008,
                InputObject: 0x9ed6),
        ],
        [
            // Set 3, scene 0: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x91f8,
                DoorPointer: 0x890a,
                DoorSlot: 0,
                CameraX: 1536,
                CameraY: 512,
                SamusYFromTop: 128,
                SamusXFromCenter: 48,
                Duration: 256,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.LandingSiteSky,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.HorizontalShinespark,
                Items: 0xf32d,
                Missiles: 85,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 999,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9ebe),
            // Set 3, scene 1: room/equipment/setup records share this index.
            new(
                RoomPointer: 0xd0b9,
                DoorPointer: 0xa474,
                DoorSlot: 0,
                CameraX: 512,
                CameraY: 0,
                SamusYFromTop: 171,
                SamusXFromCenter: 0,
                Duration: 818,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0xf32d,
                Missiles: 85,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 999,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9ec4),
            // Set 3, scene 2: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x91f8,
                DoorPointer: 0x890a,
                DoorSlot: 0,
                CameraX: 1536,
                CameraY: 512,
                SamusYFromTop: 123,
                SamusXFromCenter: 32,
                Duration: 389,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.LandingSiteSky,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingLeft,
                Items: 0xf32d,
                Missiles: 85,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 999,
                CollectedBeams: 0x0000,
                EquippedBeams: 0x0000,
                InputObject: 0x9eca),
            // Set 3, scene 3: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x9ad9,
                DoorPointer: 0x8d42,
                DoorSlot: 1,
                CameraX: 0,
                CameraY: 1024,
                SamusYFromTop: 139,
                SamusXFromCenter: -73,
                Duration: 394,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.NoOp,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.StandingRight,
                Items: 0xf32d,
                Missiles: 85,
                SuperMissiles: 15,
                PowerBombs: 10,
                Health: 999,
                CollectedBeams: 0x1008,
                EquippedBeams: 0x1008,
                InputObject: 0x9ed0),
            // Set 3, scene 4: room/equipment/setup records share this index.
            new(
                RoomPointer: 0x91f8,
                DoorPointer: 0x890a,
                DoorSlot: 0,
                CameraX: 1536,
                CameraY: 512,
                SamusYFromTop: 139,
                SamusXFromCenter: 4,
                Duration: 512,
                RoomSetupPointer: AttractDemoRomData.RoomSetup.LandingSiteSky,
                SamusSetupPointer: AttractDemoRomData.SamusSetup.LowHealthLeft,
                Items: 0xf32d,
                Missiles: 85,
                SuperMissiles: 20,
                PowerBombs: 20,
                Health: 999,
                CollectedBeams: 0x1000,
                EquippedBeams: 0x1000,
                InputObject: 0x9edc),
        ],
    ];

    /// <summary>Returns a stock scene or its exact end-of-set sentinel without reading the ROM.</summary>
    public static AttractDemoScene? Get(int set, int scene)
    {
        if ((uint)set >= Sets.Length) throw new ArgumentOutOfRangeException(nameof(set));
        if ((uint)scene > Sets[set].Length) throw new ArgumentOutOfRangeException(nameof(scene));
        return scene == Sets[set].Length ? null : Sets[set][scene];
    }
}
