using System.Security.Cryptography;
using System.Text.Json;
using SuperMetroid.Core.Audio;
using SuperMetroid.Core.Hardware;
using static SuperMetroid.AssetExtraction.SpcExtractionData;

namespace SuperMetroid.AssetExtraction;

/// <summary>
/// Build-stage extractor for the game's exact SPC upload streams and their inspectable
/// derivatives. Lossless <c>.spcu</c> files retain native provenance while decoded music/SFX
/// programs and instrument records become editable definitions; a deduplicated stable-ID WAV
/// catalog supplies every runtime sample. This deliberately makes authored audio replacement
/// independent from the managed sequencer and mixer mechanics.
/// </summary>
public static class SpcAudioAssetExtractor
{

    /// <summary>Extracts runtime audio directly from a user's cartridge, without raw files or an upstream checkout.</summary>
    public static AudioAssetManifest Extract(CartridgeImportAddressSpace cartridge, string audioDirectory)
    {
        ArgumentNullException.ThrowIfNull(cartridge);
        return Extract(definition => SpcUploadStreamReader.Read(cartridge, definition.SnesAddress, includeExecutionAddress: true), audioDirectory);
    }

    /// <summary>Extracts and validates every defined SPC upload stream, decoded program, instrument, and deduplicated sample asset.</summary>
    /// <param name="readStream">Reader that supplies one complete native upload stream for each catalog definition.</param>
    /// <param name="audioDirectory">Destination directory for streams, decoded definitions, samples, and the generated manifest.</param>
    /// <returns>The validated runtime audio manifest written to the destination.</returns>
    internal static AudioAssetManifest Extract(Func<AudioUploadAssetDefinition, byte[]> readStream, string audioDirectory)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(audioDirectory);
        audioDirectory = Path.GetFullPath(audioDirectory);

        string streamsDirectory = Path.Combine(audioDirectory, "streams");
        string samplesDirectory = Path.Combine(audioDirectory, "samples");
        Directory.CreateDirectory(streamsDirectory);
        // This directory is wholly generated by this extractor. Rebuilding it atomically at
        // the directory level prevents obsolete per-bank WAVs from masquerading as live assets.
        if (Directory.Exists(samplesDirectory))
            Directory.Delete(samplesDirectory, recursive: true);
        Directory.CreateDirectory(samplesDirectory);

        List<AudioUploadManifestEntry> uploads = [];
        Dictionary<int, byte[]> sourceStreams = [];
        foreach (AudioUploadAssetDefinition definition in AudioAssetCatalogData.All)
        {
            byte[] stream = readStream(definition);
            ValidateUploadStream(stream, definition.Name);
            string relativePath = Path.Combine("streams", $"{definition.DataIndex:X2}-{definition.Name}.spcu");
            File.WriteAllBytes(Path.Combine(audioDirectory, relativePath), stream);
            sourceStreams.Add(definition.SnesAddress, stream);
            uploads.Add(new AudioUploadManifestEntry(
                definition.Name,
                definition.SnesAddress,
                definition.DataIndex,
                relativePath.Replace('\\', '/'),
                stream.Length,
                Convert.ToHexString(SHA256.HashData(stream))));
        }

        byte[] commonRam = new byte[SpcDriverData.ApuRamSize];
        bool[] commonWritten = new bool[SpcDriverData.ApuRamSize];
        ApplyUpload(commonRam, commonWritten, sourceStreams[AudioAssetCatalogData.Common.SnesAddress]);

        var canonicalSamples = new CanonicalSampleBuilder(audioDirectory, samplesDirectory);
        List<AudioBankMetadata> banks =
        [
            ExtractBankMetadata(
                AudioAssetCatalogData.Common,
                commonRam,
                commonWritten,
                canonicalSamples,
                includeTrackPointers: false),
        ];
        foreach (AudioUploadAssetDefinition definition in AudioAssetCatalogData.Music)
        {
            byte[] ram = (byte[])commonRam.Clone();
            bool[] written = (bool[])commonWritten.Clone();
            ApplyUpload(ram, written, sourceStreams[definition.SnesAddress]);
            banks.Add(ExtractBankMetadata(
                definition,
                ram,
                written,
                canonicalSamples,
                includeTrackPointers: true));
        }

        IReadOnlyList<AudioSoundLibraryMetadata> soundLibraries = ExtractSoundLibraries(
            commonRam,
            commonWritten,
            out IReadOnlyList<AudioSoundProgramMetadata> soundPrograms);
        AudioAssetManifest manifest = new(
            AudioAssetManifest.CurrentFormatVersion,
            uploads,
            canonicalSamples.Metadata,
            banks,
            soundPrograms,
            soundLibraries);
        // Stream the UTF-8 JSON into the file; the manifest is large enough that one
        // intermediate string per install dominated extraction allocation.
        using (var output = File.Create(Path.Combine(audioDirectory, ExtractedAudioAssetCatalog.ManifestFileName)))
            JsonSerializer.Serialize(output, manifest, AudioAssetJson.Options);
        return manifest;
    }

    /// <summary>Decodes one uploaded SPC bank into track, instrument, and canonical sample metadata.</summary>
    /// <param name="definition">Identity and source address of the upload being decoded.</param>
    /// <param name="ram">Reconstructed APU RAM after applying the upload stream.</param>
    /// <param name="written">Bitmap identifying bytes supplied by the upload.</param>
    /// <param name="canonicalSamples">Builder that writes and deduplicates decoded WAV samples.</param>
    /// <param name="includeTrackPointers">Whether this bank contains the music track pointer table.</param>
    /// <returns>Decoded bank metadata for the audio manifest.</returns>
    private static AudioBankMetadata ExtractBankMetadata(
        AudioUploadAssetDefinition definition,
        byte[] ram,
        bool[] written,
        CanonicalSampleBuilder canonicalSamples,
        bool includeTrackPointers)
    {
        List<ushort> trackPointers = [];
        if (includeTrackPointers)
        {
            int tableAddress = SpcDriverData.Ram.DefaultMusicPointer;
            int firstFollowingContent = SpcDriverData.ApuRamSize;
            for (int track = 0; track < MaximumTrackPointerCount; track++)
            {
                int entryAddress = tableAddress + track * 2;
                if (entryAddress >= firstFollowingContent)
                    break;
                ushort pointer = ReadWord(ram, entryAddress);
                if (pointer != 0 && !written[pointer])
                    throw new InvalidDataException(
                        $"{definition.Name} track {track} points outside uploaded content at ${pointer:X4}.");
                trackPointers.Add(pointer);
                // Music data may precede the table, but the first pointer at or above the
                // table is the exact boundary immediately following its final entry. Stop
                // there instead of misreading that track's phrase-flow words as more tracks.
                if (pointer >= tableAddress && pointer < firstFollowingContent)
                    firstFollowingContent = pointer;
            }
            if (firstFollowingContent == SpcDriverData.ApuRamSize)
                throw new InvalidDataException($"{definition.Name} track table has no following-content boundary.");
        }
        SpcMusicDefinitionBundle music = includeTrackPointers
            ? SpcMusicDefinitionCodec.DecodeBank(
                definition.DataIndex,
                trackPointers,
                ram,
                written)
            : new([], [], []);

        List<AudioInstrumentMetadata> instruments = [];
        int instrumentCount = SpcDriverData.Ram.InstrumentCount;
        for (int instrument = 0; instrument < instrumentCount; instrument++)
        {
            int address = SpcDriverData.Ram.InstrumentTable +
                instrument * SpcDriverData.Ram.InstrumentRecordSize;
            byte source = ram[address];
            instruments.Add(new AudioInstrumentMetadata(
                instrument,
                (source & SpcDriverData.Instruments.NoiseMarker) != 0,
                source,
                ram[address + 1],
                ram[address + 2],
                ram[address + 3],
                unchecked((ushort)((ram[address + 4] << 8) | ram[address + 5]))));
        }

        List<AudioSampleMetadata> samples = [];
        ushort firstSampleAddress = ReadWord(ram, BrrDirectoryAddress);
        int directoryBytes = firstSampleAddress - BrrDirectoryAddress;
        if (directoryBytes <= 0 || directoryBytes % BrrDirectoryEntrySize != 0 ||
            directoryBytes / BrrDirectoryEntrySize > byte.MaxValue + 1)
        {
            throw new InvalidDataException(
                $"{definition.Name} has invalid BRR directory boundary ${firstSampleAddress:X4}.");
        }
        int sourceCount = directoryBytes / BrrDirectoryEntrySize;
        for (int source = 0; source < sourceCount; source++)
        {
            int directory = BrrDirectoryAddress + source * BrrDirectoryEntrySize;
            ushort start = ReadWord(ram, directory);
            ushort loop = ReadWord(ram, directory + 2);
            if (start == 0 || !written[start])
                continue;
            if (!TryDecodeBrr(ram, written, start, loop, out short[] pcm, out int blocks, out int? loopSample))
                continue;

            string sampleId = canonicalSamples.Add(
                definition.DataIndex,
                unchecked((byte)source),
                pcm,
                loopSample);
            samples.Add(new AudioSampleMetadata(
                unchecked((byte)source), start, loop, blocks, sampleId));
        }

        return new AudioBankMetadata(
            definition.Name,
            definition.DataIndex,
            definition.SnesAddress,
            trackPointers,
            music.Tracks,
            music.Phrases,
            music.Programs,
            instruments,
            samples);
    }

    /// <summary>Decodes every configured SFX library and deduplicates programs by their APU address.</summary>
    /// <param name="commonRam">Reconstructed common APU RAM containing SFX programs.</param>
    /// <param name="commonWritten">Bitmap identifying uploaded common-RAM bytes.</param>
    /// <param name="programs">Receives the unique decoded programs referenced by all libraries.</param>
    /// <returns>Sound-effect command libraries with channel-to-program bindings.</returns>
    private static List<AudioSoundLibraryMetadata> ExtractSoundLibraries(
        byte[] commonRam,
        bool[] commonWritten,
        out IReadOnlyList<AudioSoundProgramMetadata> programs)
    {
        List<AudioSoundLibraryMetadata> libraries = [];
        Dictionary<ushort, AudioSoundProgramMetadata> programsByAddress = [];
        for (int library = 0; library < SpcDriverData.SoundEffects.LibraryCount; library++)
        {
            int commandCount = SpcSoundEffectTables.CommandCount(library);
            List<AudioSoundEffectMetadata> effects = [];
            for (int index = 0; index < commandCount; index++)
            {
                ushort streamPointer = SpcSoundEffectTables.StreamPointer(library, index + 1);
                byte configuration = SpcSoundEffectTables.Configuration(library, index + 1);
                int voiceCount = SpcSoundEffectTables.GetVoiceCount(library, configuration);
                var channelPrograms = new string[voiceCount];
                for (int channel = 0; channel < voiceCount; channel++)
                {
                    int pointerAddress = streamPointer + channel * 2;
                    if (pointerAddress > ushort.MaxValue - 1 ||
                        !commonWritten[pointerAddress] || !commonWritten[pointerAddress + 1])
                    {
                        throw new InvalidDataException(
                            $"SFX library {library + 1} command ${index + 1:X2} channel {channel} " +
                            $"pointer at ${pointerAddress:X4} is outside common uploaded content.");
                    }
                    ushort programAddress = ReadWord(commonRam, pointerAddress);
                    if (!programsByAddress.TryGetValue(programAddress, out AudioSoundProgramMetadata? program))
                    {
                        string id = $"sfx-program-{programAddress:x4}";
                        program = SpcSoundEffectProgramCodec.Decode(
                            id,
                            programAddress,
                            commonRam,
                            commonWritten);
                        programsByAddress.Add(programAddress, program);
                    }
                    channelPrograms[channel] = program.Id;
                }
                effects.Add(new AudioSoundEffectMetadata(
                    unchecked((byte)(index + 1)),
                    $"sfx-{library + 1}-{index + 1:x2}",
                    streamPointer,
                    configuration,
                    channelPrograms));
            }
            libraries.Add(new AudioSoundLibraryMetadata(library + 1, effects));
        }
        programs = programsByAddress.Values.OrderBy(program => program.Address).ToArray();
        return libraries;
    }

    /// <summary>Builds an exact finite PCM prefix and recurring loop from BRR predictor states.</summary>
    internal static bool TryDecodeBrr(
        byte[] ram,
        bool[] written,
        ushort start,
        ushort loop,
        out short[] pcm,
        out int blockCount,
        out int? loopSampleIndex)
    {
        List<short> samples = [];
        HashSet<ushort> blockAddresses = [];
        Dictionary<(int Old, int Older), int> loopHistories = [];
        int address = start;
        int old = 0;
        int older = 0;
        bool followingLoop = false;
        blockCount = 0;
        while (samples.Count < BrrExtractionLimits.MaximumDecodedLoopSamples)
        {
            if (!followingLoop && blockCount >= MaximumBrrBlocks)
                break;
            if (address > ushort.MaxValue - BrrBlockByteLength)
                break;
            for (int index = 0; index < BrrBlockByteLength; index++)
            {
                if (!written[address + index])
                    goto Invalid;
            }

            blockAddresses.Add(unchecked((ushort)address));
            byte header = ram[address];
            int shift = header >> 4;
            int filter = (header >> 2) & 3;
            if (address == loop)
            {
                // A loop is repeatable only when it returns to the same predictor
                // history, not merely the same BRR address. Filter zero discards both
                // history words, so its entry state can be normalized immediately.
                var history = filter == 0 ? (0, 0) : (old, older);
                if (followingLoop && loopHistories.TryGetValue(history, out int repeatAt))
                {
                    pcm = [.. samples];
                    loopSampleIndex = repeatAt;
                    return true;
                }
                loopHistories.TryAdd(history, samples.Count);
            }
            for (int sampleIndex = 0; sampleIndex < PcmSampleFormat.StreamingWindowSampleCount; sampleIndex++)
            {
                byte packed = ram[address + 1 + sampleIndex / 2];
                int sample = (sampleIndex & 1) == 0 ? packed >> 4 : packed & 0x0f;
                if (sample > 7)
                    sample -= 16;
                sample = shift <= 0x0c ? (sample << shift) >> 1 : (sample >> 3) << 12;
                sample += filter switch
                {
                    0 => 0,
                    1 => old + (-old >> 4),
                    2 => 2 * old + ((3 * -old) >> 5) - older + (older >> 4),
                    3 => 2 * old + ((13 * -old) >> 6) - older + ((3 * older) >> 4),
                    _ => throw new InvalidDataException($"Impossible BRR filter {filter}."),
                };
                sample = Math.Clamp(sample, short.MinValue, short.MaxValue);
                sample = unchecked((short)((sample & 0x7fff) << 1)) >> 1;
                older = old;
                old = sample;
                samples.Add(unchecked((short)sample));
            }
            address += BrrBlockByteLength;
            if (!followingLoop) blockCount++;
            if ((header & 1) != 0)
            {
                if ((header & 2) == 0)
                {
                    pcm = [.. samples];
                    loopSampleIndex = null;
                    return true;
                }
                if (!blockAddresses.Contains(loop)) goto Invalid;
                // Keep transient loop passes in the WAV prefix. Once the exact
                // history repeats, the remaining cycle is ordinary replaceable PCM;
                // the runtime needs neither a BRR decoder nor special loop effects.
                followingLoop = true;
                address = loop;
            }
        }

        if (followingLoop)
            throw new InvalidDataException(
                $"BRR sample ${start:X4} loop ${loop:X4} did not reach a repeated decoder state " +
                $"within {BrrExtractionLimits.MaximumDecodedLoopSamples} PCM frames.");

    Invalid:
        pcm = [];
        blockCount = 0;
        loopSampleIndex = null;
        return false;
    }

    /// <summary>Checks that an SPC upload stream has valid records and a legal terminator.</summary>
    /// <param name="stream">Raw length/address/data records to validate.</param>
    /// <param name="name">Upload name included in invalid-stream errors.</param>
    private static void ValidateUploadStream(ReadOnlySpan<byte> stream, string name)
    {
        byte[] scratch = new byte[SpcDriverData.ApuRamSize];
        bool[] written = new bool[SpcDriverData.ApuRamSize];
        try
        {
            ApplyUpload(scratch, written, stream);
        }
        catch (InvalidDataException exception)
        {
            throw new InvalidDataException($"Raw audio asset '{name}' is not a valid SPC upload stream.", exception);
        }
    }

    /// <summary>Applies upload records to APU RAM and marks every written byte.</summary>
    /// <param name="ram">Mutable APU RAM destination.</param>
    /// <param name="written">Parallel bitmap updated for each copied range.</param>
    /// <param name="stream">Raw SPC upload stream, including its terminating record.</param>
    private static void ApplyUpload(byte[] ram, bool[] written, ReadOnlySpan<byte> stream)
    {
        int offset = 0;
        for (;;)
        {
            if (offset > stream.Length - 2)
                throw new InvalidDataException("SPC upload ended before its terminating length word.");
            ushort length = unchecked((ushort)(stream[offset] | (stream[offset + 1] << 8)));
            offset += 2;
            if (length == 0)
            {
                // Retail assets retain the two-byte SPC execution address consumed by the
                // upload handshake after its zero-length marker. The managed driver already
                // runs, so playback ignores it while extraction preserves it byte-for-byte.
                if (stream.Length - offset is not 0 and not 2)
                    throw new InvalidDataException($"SPC upload has {stream.Length - offset} unexpected bytes after its terminator.");
                return;
            }
            if (offset > stream.Length - 2)
                throw new InvalidDataException("SPC upload ended before a destination word.");
            ushort destination = unchecked((ushort)(stream[offset] | (stream[offset + 1] << 8)));
            offset += 2;
            if (length > stream.Length - offset)
                throw new InvalidDataException($"SPC upload record ${destination:X4} overruns its source stream.");
            if (destination + length > ram.Length)
                throw new InvalidDataException($"SPC upload record ${destination:X4}+${length:X4} overruns APU RAM.");
            stream.Slice(offset, length).CopyTo(ram.AsSpan(destination, length));
            Array.Fill(written, true, destination, length);
            offset += length;
        }
    }

    /// <summary>Reads a little-endian word from reconstructed APU memory.</summary>
    /// <param name="bytes">APU memory bytes.</param>
    /// <param name="address">Address of the low byte.</param>
    /// <returns>The decoded 16-bit word.</returns>
    private static ushort ReadWord(byte[] bytes, int address) =>
        unchecked((ushort)(bytes[address] | (bytes[address + 1] << 8)));

    /// <summary>
    /// Assigns the first cartridge occurrence of a unique waveform/loop pair a readable,
    /// durable identity. Content hashes are only deduplication and integrity mechanisms:
    /// replacing a WAV later does not force callers to rename its sample ID.
    /// </summary>
    private sealed class CanonicalSampleBuilder
    {
        /// <summary>Root audio directory used to store manifest-relative sample paths.</summary>
        private readonly string audioDirectory;
        /// <summary>Directory receiving canonical WAV files.</summary>
        private readonly string samplesDirectory;
        /// <summary>Maps sample-rate, loop, and PCM identity to the stable ID already assigned.</summary>
        private readonly Dictionary<string, string> idsByContent = new(StringComparer.Ordinal);
        /// <summary>Canonical WAV metadata in first cartridge occurrence order.</summary>
        private readonly List<AudioCanonicalSampleMetadata> metadata = [];

        /// <summary>Creates a builder for canonical samples under the audio installation directory.</summary>
        /// <param name="audioDirectory">Root directory used for relative manifest paths.</param>
        /// <param name="samplesDirectory">Destination directory for the generated WAV files.</param>
        internal CanonicalSampleBuilder(string audioDirectory, string samplesDirectory)
        {
            this.audioDirectory = audioDirectory;
            this.samplesDirectory = samplesDirectory;
        }

        /// <summary>Gets canonical sample metadata in the order each unique sample was first encountered.</summary>
        internal IReadOnlyList<AudioCanonicalSampleMetadata> Metadata => metadata;

        /// <summary>Writes a new unique PCM sample or returns the ID assigned to matching content.</summary>
        /// <param name="dataIndex">Cartridge audio upload index that first references the sample.</param>
        /// <param name="source">BRR directory slot containing the sample.</param>
        /// <param name="pcm">Decoded mono signed 16-bit samples.</param>
        /// <param name="loopSampleIndex">Decoded loop position, or <see langword="null"/> for a one-shot sample.</param>
        /// <returns>The stable sample ID used by bank metadata.</returns>
        internal string Add(byte dataIndex, byte source, short[] pcm, int? loopSampleIndex)
        {
            byte[] pcmBytes = new byte[checked(pcm.Length * sizeof(short))];
            Buffer.BlockCopy(pcm, 0, pcmBytes, 0, pcmBytes.Length);
            string contentKey = $"{PcmSampleFormat.StockSampleRate}:{loopSampleIndex?.ToString() ?? "-"}:" +
                Convert.ToHexString(SHA256.HashData(pcmBytes));
            if (idsByContent.TryGetValue(contentKey, out string? existingId))
                return existingId;

            string id = $"sample-{dataIndex:X2}-{source:X2}".ToLowerInvariant();
            string absolutePath = Path.Combine(samplesDirectory, id + ".wav");
            PcmWaveFile.WriteMonoPcm16(absolutePath, PcmSampleFormat.StockSampleRate, pcm);
            byte[] waveBytes = File.ReadAllBytes(absolutePath);
            string relativePath = Path.GetRelativePath(audioDirectory, absolutePath).Replace('\\', '/');
            metadata.Add(new AudioCanonicalSampleMetadata(
                id,
                relativePath,
                PcmSampleFormat.StockSampleRate,
                pcm.Length,
                loopSampleIndex,
                Convert.ToHexString(SHA256.HashData(waveBytes))));
            idsByContent.Add(contentKey, id);
            return id;
        }
    }
}
