using SuperMetroid.Core.Assets;
using SuperMetroid.Core.Game;
using SuperMetroid.Core.Hardware;
using SuperMetroid.Core.Rendering;

internal static partial class Program
{
    /// <summary>
    /// Verifies the shared FX-record schema, representative native type discriminants,
    /// typed blending state, and both renderable layer-three table lookups.
    /// </summary>
    static void VerifyRoomFxRomData()
    {
        AssertEqual(16, RoomFxRomData.Record.ByteCount, "room FX record width");
        AssertEqual(9, RoomFxRomData.Record.TypeOffset, "room FX type field");
        AssertEqual(11, RoomFxRomData.Record.Layer3LayerBlendConfigurationOffset,
            "room FX layer-three blend field");
        AssertEqual(15, RoomFxRomData.Record.PaletteBlendOffset,
            "room FX palette-blend field");
        AssertEqual(23, RoomFxRomData.ScrollingSky.SectionCount,
            "scrolling-sky section count");

        (RoomFxType Type, ushort NativeValue)[] representativeTypes =
        [
            (RoomFxType.Water, 0x0006),
            (RoomFxType.Lava, 0x0002),
            (RoomFxType.Acid, 0x0004),
            (RoomFxType.ScrollingSky, 0x0020),
            (RoomFxType.CeresHaze, 0x002c),
            (RoomFxType.CeresRidley, 0x0028),
            (RoomFxType.CeresElevator, 0x002a),
        ];
        foreach ((RoomFxType type, ushort nativeValue) in representativeTypes)
            AssertEqual(nativeValue, (ushort)type, $"{type} native room-FX value");

        VerifyRoomLayer3FxTypes();
        VerifyAreaAnimatedTileObjectDefinitions();
        VerifyRoomFxAnimatedTileMechanicsDefinitions();
        VerifyRoomFxAnimatedTileArtwork();
        VerifyRoomFxLayer3Tilemaps();
        VerifyRoomFxPaletteBlends();
        VerifyRetailRoomFxInventory();
        VerifyFxValidationBoundaries();

        Console.WriteLine(
            "  Room FX: shared record/table catalog, typed blending, liquid rise " +
            "sound/shake, sky, haze, Ceres, rain, and fog states agree.");
    }

    private static void VerifyFxValidationBoundaries()
    {
        var rom = SuperMetroid.AssetExtraction.CartridgeImportAddressSpace.LoadRetailRom(Path.GetFullPath("Super Metroid.smc"));
        AssertEqual(SuperMetroid.AssetExtraction.SupportedCartridge.Sha256.ToUpperInvariant(),
            Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(rom.Rom)), "FX validation oracle revision");
        VerifyRoomFxTypeValidation(rom);
        VerifyLayerBlendValidation(rom);
    }

    private static void VerifyRoomFxTypeValidation(ISnesAddressSpace rom)
    {
        // Original pre-conversion enum membership, independently cross-checked with
        // the native function pointer table. Zero is deliberately named; the other
        // entries targeting the same RTL were never accepted by this port boundary.
        ushort[] original = [0, 2, 4, 6, 8, 10, 12, 32, 34, 36, 38, 40, 42, 44];
        AssertTrue(Enum.GetValues<RoomFxType>().Select(x => (ushort)x).SequenceEqual(original),
            "All named room FX identities retain their original values");
        AssertEqual((ushort)0xac18, ReadVerificationWord(rom, 0x89ac49), "Native room FX dispatcher table operand");
        for (int slot = 0; slot <= 44; slot += 2)
        {
            ushort pointer = ReadVerificationWord(rom, 0x83ac18 + slot);
            AssertEqual(original.Contains((ushort)slot), slot == 0 || pointer != 0xb278,
                "Original named membership matches native routines excluding unnamed RTL slots");
        }
        for (int value = 0; value <= byte.MaxValue; value++)
        {
            if (original.Contains((ushort)value))
                AssertEqual((ushort)value, (ushort)RoomFxTypes.FromCartridge((byte)value, "record $9000"),
                    "Room FX identity conversion preserves every accepted byte");
            else
            {
                var error = AssertThrows<NotSupportedException>(
                    () => RoomFxTypes.FromCartridge((byte)value, "record $9000"), "Undefined room FX rejected");
                AssertTrue(error.Message.Contains($"${value:X2}", StringComparison.Ordinal) &&
                    error.Message.Contains("$9000", StringComparison.Ordinal), "Room FX failure retains value/context");
            }
        }
    }

    private static void VerifyLayerBlendValidation(ISnesAddressSpace rom)
    {
        // Original pre-conversion enum membership, not generated by the new validator.
        ushort[] original = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26,
            28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52];
        AssertTrue(Enum.GetValues<LayerBlendingConfiguration>().Select(x => (ushort)x).SequenceEqual(original),
            "All named blend identities retain their original values");
        AssertEqual((ushort)0x803e, ReadVerificationWord(rom, 0x88800e), "Native blending dispatcher operand");
        AssertEqual((ushort)0x8074, ReadVerificationWord(rom, 0x88803e), "First target marks original table end");
        foreach (ushort offset in original)
        {
            ushort target = ReadVerificationWord(rom, 0x88803e + offset);
            AssertTrue(target >= 0x8074 && target <= 0x8156, "Native slot points into its blending routines");
        }
        for (int value = 0; value <= ushort.MaxValue; value++)
        {
            var configuration = (LayerBlendingConfiguration)value;
            bool accepted = original.Contains((ushort)value);
            if (accepted) LayerBlendingConfigurations.Validate(configuration, "blend");
            else
            {
                var error = AssertThrows<ArgumentOutOfRangeException>(
                    () => LayerBlendingConfigurations.Validate(configuration, "blend"), "Undefined host blend rejected");
                AssertEqual("blend", error.ParamName!, "Host blend failure retains parameter name");
                AssertEqual(configuration, (LayerBlendingConfiguration)error.ActualValue!, "Host blend failure retains value");
            }
            if (value > byte.MaxValue) continue;
            if (accepted)
                AssertEqual(configuration, LayerBlendingConfigurations.FromCartridge((byte)value, "record $9000"),
                    "Cartridge blend preserves accepted identity");
            else
            {
                var error = AssertThrows<NotSupportedException>(
                    () => LayerBlendingConfigurations.FromCartridge((byte)value, "record $9000"), "Undefined cartridge blend rejected");
                AssertTrue(error.Message.Contains($"{value:X4}", StringComparison.Ordinal) &&
                    error.Message.Contains("$9000", StringComparison.Ordinal), "Cartridge blend failure retains value/context");
            }
        }
    }

    private static void VerifyRoomLayer3FxTypes()
    {
        var bus = new TestAddressSpace();
        var vram = new SnesVram();
        var cgram = new SnesCgram();
        var presentation = RetailPresentationFixture();
        var state = new RoomLayer3FxState
        {
            Layer3Tilemaps = presentation.RoomFxLayer3Tilemaps,
            PaletteBlendColors = presentation.RoomFxPaletteBlends,
            AnimatedTileArtwork = presentation.RoomFxAnimatedTiles,
        };
        const ushort record = 0x9400;
        int recordAddress = RoomFxRomData.Banks.RoomDefinitions | record;
        WriteTestWord(bus, recordAddress + RoomFxRomData.Record.DoorPointerOffset, 0);
        bus.WriteByte(
            recordAddress + RoomFxRomData.Record.Layer3LayerBlendConfigurationOffset,
            (byte)LayerBlendingConfiguration.NormalGameplay);

        RoomFxType[] nonLayer3Types =
        [
            RoomFxType.ScrollingSky,
            RoomFxType.CeresHaze,
            RoomFxType.CeresRidley,
            RoomFxType.CeresElevator,
        ];
        foreach (RoomFxType type in nonLayer3Types)
        {
            bus.WriteByte(recordAddress + RoomFxRomData.Record.TypeOffset, (byte)type);
            LoadSyntheticRoomFx(state, bus, vram, cgram, record);
            AssertEqual(type, state.Type, $"{type} FX record type");
            AssertEqual(
                LayerBlendingConfiguration.NormalGameplay,
                state.LayerBlendConfiguration,
                $"{type} typed layer-blending configuration");
            AssertTrue(!state.IsRenderable, $"{type} does not impersonate rain/fog BG3");
        }

        VerifyRenderableLayer3Fx(bus, vram, cgram, state, record, RoomFxType.Lava);
        VerifyRenderableLayer3Fx(bus, vram, cgram, state, record, RoomFxType.Acid);
        VerifyRenderableLayer3Fx(bus, vram, cgram, state, record, RoomFxType.Water);
        VerifyRenderableLayer3Fx(bus, vram, cgram, state, record, RoomFxType.Rain);
        VerifyRenderableLayer3Fx(bus, vram, cgram, state, record, RoomFxType.Fog);
    }

    private static void VerifyRenderableLayer3Fx(
        TestAddressSpace bus,
        SnesVram vram,
        SnesCgram cgram,
        RoomLayer3FxState state,
        ushort record,
        RoomFxType type)
    {
        bus.WriteByte(
            RoomFxRomData.Banks.RoomDefinitions |
                unchecked((ushort)(record + RoomFxRomData.Record.TypeOffset)),
            (byte)type);
        LayerBlendingConfiguration layerBlend = type switch
        {
            RoomFxType.Lava or RoomFxType.Acid =>
                LayerBlendingConfiguration.LavaAcidAdditive,
            RoomFxType.Water => LayerBlendingConfiguration.LiquidOrFogAdditive,
            RoomFxType.Rain => LayerBlendingConfiguration.Rain,
            RoomFxType.Fog => LayerBlendingConfiguration.FogAdditive,
            _ => throw new InvalidOperationException($"Unexpected renderable room FX {type}."),
        };
        bus.WriteByte(
            RoomFxRomData.Banks.RoomDefinitions |
                unchecked((ushort)(record +
                    RoomFxRomData.Record.Layer3LayerBlendConfigurationOffset)),
            (byte)layerBlend);

        LoadSyntheticRoomFx(state, bus, vram, cgram, record);
        VerifyRoomFxSharedRandomState(bus, vram, cgram, state, record, type);
        AssertEqual(RoomFxRomData.Layer3.ClearTilemapWord,
            vram.ReadWord(RoomFxRomData.Layer3.ClearDestinationWord),
            $"{type} room load clears the first gameplay BG3 FX word");
        if (type is RoomFxType.Water or RoomFxType.Lava or RoomFxType.Acid)
        {
            const ushort surfaceY = 100;
            bus.WriteByte(
                RoomFxRomData.Banks.RoomDefinitions |
                    unchecked((ushort)(record + RoomFxRomData.Record.LiquidOptionsOffset)),
                type == RoomFxType.Water
                    ? (byte)3
                    : (byte)RoomFxRomData.LavaAcid.VerticalBg2WaveOption);
            WriteTestWord(
                bus,
                RoomFxRomData.Banks.RoomDefinitions |
                    unchecked((ushort)(record + RoomFxRomData.Record.BaseYPositionOffset)),
                surfaceY);
            LoadSyntheticRoomFx(state, bus, vram, cgram, record);
            state.PrimeViewport(cameraX: 0x0100, cameraY: 0);
        }
        AssertEqual(type, state.Type, $"{type} layer-three type");
        AssertTrue(state.IsRenderable, $"{type} owns a translated layer-three plane");
        RoomLayer3FxRenderSnapshot snapshot = state.CaptureForDisplay()!.Value;
        AssertEqual(
            layerBlend,
            snapshot.LayerBlendConfiguration,
            $"{type} render snapshot retains typed blending");

        if (type is RoomFxType.Water or RoomFxType.Lava or RoomFxType.Acid)
        {
            AssertEqual(100, snapshot.WaterSurfaceScreenY,
                $"{type} surface retains room-relative scanline");
            ushort expectedOptions = type == RoomFxType.Water
                ? (ushort)3
                : RoomFxRomData.LavaAcid.VerticalBg2WaveOption;
            AssertEqual(expectedOptions, snapshot.LiquidOptions,
                $"{type} render snapshot retains its wave options");
            AssertEqual((ushort)0x009b, snapshot.VerticalScroll,
                $"{type} anchors BG3 row zero immediately below surface Y 100");

            // Give the liquid page one opaque two-bit tile and a visible blue color. The
            // exact surface assertion proves the compositor leaves the air row untouched
            // and applies the cartridge layer-three plane below it.
            vram.ExecuteWordTransfer(
                Enumerable.Repeat((ushort)1, 33 * 32).ToArray(),
                RoomFxRomData.Layer3.TilemapDestinationWord,
                wordIncrement: 1);
            var character = new byte[16];
            for (int row = 0; row < 8; row++)
                character[row * 2] = 0xff;
            vram.LoadBytes((0x4000 + 8) * 2, character);
            cgram.SetColor(1, 0x7c00);
        }
        else
        {
            // Rain/fog write BG3SC=$5C and therefore address the second page as a
            // standalone 32x32 tilemap. Give the ordinary $5800 page a red decoy and the
            // real $5C00 page a blue source. This reproduces the former HUD-clone failure:
            // indexing from $5800 sampled the first page and moved it with the effect.
            vram.ExecuteWordTransfer(
                Enumerable.Repeat((ushort)1, SnesPpuLayout.TilemapPageWordCount).ToArray(),
                RoomFxRomData.Layer3.LiquidTilemapBaseWord,
                wordIncrement: 1);
            vram.ExecuteWordTransfer(
                Enumerable.Repeat((ushort)2, SnesPpuLayout.TilemapPageWordCount).ToArray(),
                RoomFxRomData.Layer3.FullScreenAtmosphereTilemapBaseWord,
                wordIncrement: 1);
            var redDecoyCharacter = new byte[16];
            var blueEffectCharacter = new byte[16];
            for (int row = 0; row < 8; row++)
            {
                redDecoyCharacter[row * 2] = 0xff;
                blueEffectCharacter[row * 2 + 1] = 0xff;
            }
            vram.LoadBytes((0x4000 + 1 * 8) * 2, redDecoyCharacter);
            vram.LoadBytes((0x4000 + 2 * 8) * 2, blueEffectCharacter);
            cgram.SetColor(1, 0x001f);
            cgram.SetColor(2, 0x7c00);
            snapshot = snapshot with { HorizontalScroll = 0, VerticalScroll = 0 };
        }

        // The software compositor now consumes the same typed dispatcher identity as the
        // room loader. Rain and fog use different main/subscreen ownership in hardware even
        // though both resolve to additive BG3 pixels, so neither pairing may be substituted.
        var frame = new Rgba32[
            SnesGameplayFrameRenderer.Width * SnesGameplayFrameRenderer.Height];
        SnesGameplayFrameRenderer.ApplyRoomLayer3FxColorMath(
            frame, vram, cgram, snapshot);
        if (type is RoomFxType.Water or RoomFxType.Lava or RoomFxType.Acid)
        {
            int above = 90 * SnesGameplayFrameRenderer.Width + 20;
            int below = 110 * SnesGameplayFrameRenderer.Width + 20;
            AssertEqual(new Rgba32(0, 0, 0, 0), frame[above],
                $"{type} leaves pixels above its surface untouched");
            AssertTrue(frame[below].B != 0,
                $"{type} applies its visible BG3 color below the surface");

            // Negative liquid positions are the cartridge's deliberate "no visible
            // surface" sentinel. Reuse the same known-opaque tile and palette so this
            // assertion would fail if the signed boundary check regressed; an empty
            // fixture could otherwise make a broken compositor look correct by accident.
            var hiddenSurfaceFrame = new Rgba32[frame.Length];
            SnesGameplayFrameRenderer.ApplyRoomLayer3FxColorMath(
                hiddenSurfaceFrame,
                vram,
                cgram,
                snapshot with
                {
                    CurrentYPosition = ushort.MaxValue,
                    WaterSurfaceScreenY = -1,
                });
            AssertTrue(hiddenSurfaceFrame.All(pixel => pixel == default),
                $"{type} $FFFF surface suppresses the complete BG3 liquid plane");

            ushort[] bg2Scroll = type == RoomFxType.Water
                ? SnesGameplayFrameRenderer.BuildWaterBg2HorizontalScrolls(
                    snapshot,
                    bg2HorizontalScroll: 0x0200,
                    bg2VerticalScroll: 0) ?? throw new InvalidDataException(
                        "Wavy water did not publish a BG2 HDMA scroll table.")
                : SnesGameplayFrameRenderer.BuildLavaAcidBg2VerticalScrolls(
                    snapshot,
                    bg2VerticalScroll: 0x0200) ?? throw new InvalidDataException(
                        $"{type} did not publish its BG2 HDMA scroll table.");
            AssertEqual(SnesGameplayFrameRenderer.Height - SnesGameplayFrameRenderer.HudHeight,
                bg2Scroll.Length,
                $"{type} BG2 wave table covers gameplay scanlines");
            if (type == RoomFxType.Water)
            {
                AssertEqual((ushort)0x0200,
                    bg2Scroll[90 - SnesGameplayFrameRenderer.HudHeight],
                    "water leaves BG2 undistorted above the surface");
                AssertTrue(
                    bg2Scroll.Skip(101 - SnesGameplayFrameRenderer.HudHeight).Distinct().Count() > 1,
                    "water distorts BG2 below the surface");
            }
            else
            {
                AssertEqual(3, bg2Scroll.Distinct().Count(),
                    $"{type} uses the native three-value heat waveform");
                for (int frameNumber = 0;
                     frameNumber < RoomFxRomData.LavaAcid.VerticalWavePhaseDuration - 1;
                     frameNumber++)
                {
                    state.Step(bus, vram, cameraX: 0x0100, cameraY: 0, timeIsFrozen: false);
                    AssertEqual(0, state.CaptureForDisplay()!.Value.LavaAcidBg2WavePhase,
                        $"{type} heat wave retains phase before frame four");
                }
                state.Step(bus, vram, cameraX: 0x0100, cameraY: 0, timeIsFrozen: false);
                AssertEqual(15, state.CaptureForDisplay()!.Value.LavaAcidBg2WavePhase,
                    $"{type} heat wave rotates backward on frame four");
            }
        }
        else
        {
            Rgba32 firstEffectPixel = frame[
                SnesGameplayFrameRenderer.HudHeight * SnesGameplayFrameRenderer.Width];
            AssertTrue(firstEffectPixel.B != 0 && firstEffectPixel.R == 0,
                $"{type} samples the $5C00 effect page instead of the $5800 HUD page");

            var wrappedFrame = new Rgba32[frame.Length];
            SnesGameplayFrameRenderer.ApplyRoomLayer3FxColorMath(
                wrappedFrame,
                vram,
                cgram,
                snapshot with { VerticalScroll = 0x0100 });
            Rgba32 wrappedEffectPixel = wrappedFrame[
                SnesGameplayFrameRenderer.HudHeight * SnesGameplayFrameRenderer.Width];
            AssertTrue(wrappedEffectPixel.B != 0 && wrappedEffectPixel.R == 0,
                $"{type} wraps vertical scroll within its 32-row $5C00 page");
        }
        LayerBlendingConfiguration wrongBlend = type switch
        {
            RoomFxType.Lava or RoomFxType.Acid => LayerBlendingConfiguration.NormalGameplay,
            RoomFxType.Water => LayerBlendingConfiguration.NormalGameplay,
            RoomFxType.Rain => LayerBlendingConfiguration.FogAdditive,
            _ => LayerBlendingConfiguration.Rain,
        };
        AssertThrows<InvalidDataException>(
            () => SnesGameplayFrameRenderer.ApplyRoomLayer3FxColorMath(
                frame,
                vram,
                cgram,
                snapshot with { LayerBlendConfiguration = wrongBlend }),
            $"{type} rejects another FX type's layer-blending route");
    }

    // Decode the fixture's literal sixteen-byte record independently of the compiled
    // retail catalog, then exercise the same production initialization and rendering.
    private static void LoadSyntheticRoomFx(RoomLayer3FxState state, TestAddressSpace bus,
        SnesVram vram, SnesCgram cgram, ushort pointer)
    {
        int address = 0x830000 | pointer;
        byte Byte(int offset) => bus.ReadByte(address + offset);
        ushort Word(int offset) => (ushort)(Byte(offset) | Byte(offset + 1) << 8);
        state.LoadDefinition(bus, vram, cgram, new RoomFxRecordDefinition(pointer,
            Word(0), Word(2), Word(4), Word(6), Byte(8), Byte(9), Byte(10), Byte(11),
            Byte(12), Byte(13), Byte(14), Byte(15)), randomNumber: 0);
    }
}