using SuperMetroid.Core.Assets;

internal static partial class Program
{
    // Independent pre-conversion strip order at22b928b4: native simple animation
    // operands, rightward treadmill operands, complete statue strip, then spores.
    // Metadata only, captured from supported ROM; never generated by Segments.
    private static RoomFxAtlasSegment[] OriginalRoomFxAtlasSegments() =>
    [
        new(0x8791e4, 0x0040, true),
        new(0x879224, 0x0040, true),
        new(0x879264, 0x0040, true),
        new(0x8792a4, 0x0040, true),
        new(0x879164, 0x0020, true),
        new(0x879184, 0x0020, true),
        new(0x8791a4, 0x0020, true),
        new(0x8791c4, 0x0020, true),
        new(0x87a564, 0x0040, true),
        new(0x87a5a4, 0x0040, true),
        new(0x87a5e4, 0x0040, true),
        new(0x87a624, 0x0040, true),
        new(0x87a664, 0x0040, true),
        new(0x87a6a4, 0x0040, true),
        new(0x87a6e4, 0x0040, true),
        new(0x87a724, 0x0040, true),
        new(0x87a764, 0x0040, true),
        new(0x87a7a4, 0x0040, true),
        new(0x87a874, 0x0050, true),
        new(0x87a8c4, 0x0050, true),
        new(0x87a914, 0x0050, true),
        new(0x87a964, 0x0050, true),
        new(0x87a9b4, 0x0050, true),
        new(0x878e64, 0x0020, true),
        new(0x878e84, 0x0020, true),
        new(0x878ea4, 0x0020, true),
        new(0x878ec4, 0x0020, true),
        new(0x879364, 0x0600, false),
        new(0x87a7e4, 0x0030, true),
        new(0x87a814, 0x0030, true),
        new(0x87a844, 0x0030, true),
    ];

    private static void VerifyRoomFxAtlasSegmentSources(SuperMetroid.Core.Hardware.ISnesAddressSpace rom)
    {
        var expected = OriginalRoomFxAtlasSegments();
        var actual = RoomFxAnimatedTileAtlasFormat.Segments.ToArray();
        AssertEqual(expected.Length, actual.Length, "Atlas original segment count");
        var bytes = Enumerable.Range(0, 3232).Select(index => (byte)(index * 37 + index / 256)).ToArray();
        var constructor = typeof(RoomFxAnimatedTileAtlas).GetConstructor(
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance,
            null, [typeof(byte[])], null)!;
        var atlas = (RoomFxAnimatedTileAtlas)constructor.Invoke([bytes]);
        int offset = 0;
        foreach (var segment in expected)
        {
            if (segment.IsFrame)
            {
                AssertTrue(atlas.TryResolve(segment.SourceAddress, segment.ByteCount, out var data),
                    "Original standalone source resolves without a dictionary");
                AssertTrue(bytes.AsSpan(offset, segment.ByteCount).SequenceEqual(data.Span),
                    "Source selects its original editable pixel window");
                AssertThrows<InvalidDataException>(() => atlas.TryResolve(segment.SourceAddress,
                    segment.ByteCount + 1, out _), "Altered standalone geometry rejects");
            }
            offset += segment.ByteCount;
        }
        foreach (ushort header in new ushort[] { 0x854c, 0x8552, 0x8558, 0x855e })
        foreach (var frame in OriginalTourianFrames(rom, header))
        {
            int size = ReadVerificationWord(rom, 0x870002 + header);
            AssertTrue(atlas.TryResolve(frame.Source, size, out var data), "Original shared statue window resolves");
            AssertTrue(bytes.AsSpan(1552 + frame.Source - 0x879364, size).SequenceEqual(data.Span),
                "Statue alias still selects its original strip window");
            AssertThrows<InvalidDataException>(() => atlas.TryResolve(frame.Source, size + 1, out _),
                "Altered statue geometry rejects after streamed lookup");
        }
        foreach (int missing in new[] { int.MinValue, 0, 0x878e63, 0x878e65, 0x87a9b5, int.MaxValue })
            AssertTrue(!atlas.TryResolve(missing, 32, out _), "Non-frame source remains unresolved");
        for (int index = 0; index < expected.Length; index++)
            AssertEqual(expected[index].SourceAddress, actual[index].SourceAddress, "Atlas source order");
    }

    private static void VerifyRoomFxAtlasSegmentSizes()
    {
        var expected = OriginalRoomFxAtlasSegments();
        var actual = RoomFxAnimatedTileAtlasFormat.Segments.ToArray();
        for (int index = 0; index < expected.Length; index++)
            AssertEqual(expected[index].ByteCount, actual[index].ByteCount, "Atlas segment length");
        AssertEqual(3232, actual.Sum(segment => segment.ByteCount), "Complete original PNG byte geometry");
    }

    private static void VerifyRoomFxAtlasSegmentRoles()
    {
        var expected = OriginalRoomFxAtlasSegments();
        var actual = RoomFxAnimatedTileAtlasFormat.Segments.ToArray();
        for (int index = 0; index < expected.Length; index++)
            AssertEqual(expected[index].IsFrame, actual[index].IsFrame, "Atlas standalone frame or shared strip");
        AssertTrue(RoomFxAnimatedTileAtlasFormat.Segments is not ICollection<RoomFxAtlasSegment>,
            "Segments are streamed without a materialized collection");
    }
}
