using SuperMetroid.Core.Game;
using SuperMetroid.Core.Hardware;

/// <summary>Expected retail area-map export paths, cartridge tilemap addresses, and reveal-mask coverage counts for verification.</summary>
internal static class AreaMapAssetVerificationDefinitions
{
    /// <summary>Repository-relative root generated by the deterministic map extractor.</summary>
    public const string AssetRoot = "csharp/test-temp/verification-area-map-export";

    /// <summary>Expected tilemap addresses in cartridge area-index order.</summary>
    public static ReadOnlySpan<int> TilemapAddresses =>
    [
        0xb59000,
        0xb58000,
        0xb5a000,
        0xb5b000,
        0xb5c000,
        0xb5d000,
        0xb5e000,
    ];

    /// <summary>Expected station-visible cell counts in cartridge area-index order.</summary>
    public static ReadOnlySpan<int> StationVisibleCellCounts => [183, 168, 230, 45, 225, 45, 15];

    /// <summary>Expected secret-only cell counts in cartridge area-index order.</summary>
    public static ReadOnlySpan<int> SecretOnlyCellCounts => [50, 86, 131, 24, 53, 34, 0];
}

internal static partial class Program
{
    /// <summary>
    /// Compares every freshly exported lossless area-map artifact with its originating cartridge
    /// range and checks the station-visible and secret-only coverage counts.
    /// </summary>
    static void VerifyAreaMapAssets()
    {
        string root = Path.GetFullPath(AreaMapAssetVerificationDefinitions.AssetRoot);
        string romPath = Path.GetFullPath("Super Metroid.smc");
        AssertEqual(AreaIds.RetailCount, MapAssetExtractor.Extract(romPath, root), "exported area-map count");
        SuperMetroidAddressSpace bus = SuperMetroid.AssetExtraction.CartridgeImportAddressSpaceTooling.LoadRetailRom(romPath);
        foreach (AreaId area in Enum.GetValues<AreaId>())
        {
            int index = AreaIds.ToIndex(area);
            AreaMapCartridgeData map = SuperMetroid.AssetExtraction.AreaMapImporter.Load(bus, area);
            AssertEqual(AreaMapAssetVerificationDefinitions.TilemapAddresses[index],
                map.TilemapAddress,
                $"{area} tilemap address");

            string stem = Path.Combine(root, "areas", MapAssetExtractor.FileStem(area));
            string tilemapPath = stem + ".tilemap.bin";
            string revealPath = stem + ".station-reveal-mask.bin";
            AssertTrue(File.Exists(stem + ".coverage.png"), $"{area} coverage image exported");
            AssertSequenceEqual(map.RawTilemapBytes, File.ReadAllBytes(tilemapPath),
                $"{area} extracted tilemap bytes");
            AssertSequenceEqual(map.StationRevealMaskBytes, File.ReadAllBytes(revealPath),
                $"{area} extracted station mask bytes");

            int publicCount = 0;
            int secretCount = 0;
            for (int y = 0; y < AreaMapLayout.HeightInTiles; y++)
            {
                for (int x = 0; x < AreaMapLayout.WidthInTiles; x++)
                {
                    bool discoverable = map.IsDiscoverable(x, y);
                    bool stationVisible = map.IsRevealedByMapStation(x, y);
                    AssertTrue(!stationVisible || discoverable,
                        $"{area} station mask cell ({x},{y}) exists in tilemap");
                    publicCount += stationVisible ? 1 : 0;
                    secretCount += discoverable && !stationVisible ? 1 : 0;
                }
            }
            AssertEqual(AreaMapAssetVerificationDefinitions.StationVisibleCellCounts[index],
                publicCount,
                $"{area} station-visible cell count");
            AssertEqual(AreaMapAssetVerificationDefinitions.SecretOnlyCellCounts[index],
                secretCount,
                $"{area} secret-only cell count");
        }

        AreaMapCartridgeData brinstar = SuperMetroid.AssetExtraction.AreaMapImporter.Load(bus, AreaId.Brinstar);
        AssertTrue(brinstar.IsRevealedByMapStation(9, 1),
            "representative Brinstar public map cell");
        AssertTrue(brinstar.IsDiscoverable(23, 2) &&
                   !brinstar.IsRevealedByMapStation(23, 2),
            "representative Brinstar secret-only map cell");
        Console.WriteLine(
            "  Area maps: seven tilemaps/masks and coverage counts agree.");
    }
}
