using System.Text.Json;
using SuperMetroid.Core.Game;
using SuperMetroid.Core.Hardware;

internal static class AreaMapAssetVerificationDefinitions
{
    /// <summary>Repository-relative root generated by the deterministic map extractor.</summary>
    public const string AssetRoot = "standalone-assets/maps";

    /// <summary>Expected tilemap addresses in cartridge area-index order.</summary>
    public static ReadOnlySpan<int> TilemapAddresses =>
    [
        0xb59000,
        0xb58000,
        0xb5a000,
        0xb5b000,
        0xb5c000,
        0xb5d000,
        0xb5e000,
    ];

    /// <summary>Expected station-visible cell counts in cartridge area-index order.</summary>
    public static ReadOnlySpan<int> StationVisibleCellCounts => [183, 168, 230, 45, 225, 45, 15];

    /// <summary>Expected secret-only cell counts in cartridge area-index order.</summary>
    public static ReadOnlySpan<int> SecretOnlyCellCounts => [50, 86, 131, 24, 53, 34, 0];
}

internal static partial class Program
{
    /// <summary>
    /// Compares every committed lossless area-map artifact with its originating cartridge
    /// range and checks the decoded room-placement inventory used by map tooling.
    /// </summary>
    static void VerifyAreaMapAssets()
    {
        string root = Path.GetFullPath(AreaMapAssetVerificationDefinitions.AssetRoot);
        string manifestPath = Path.Combine(root, "manifest.json");
        string roomsPath = Path.Combine(root, "room-placements.json");
        AssertTrue(File.Exists(manifestPath), "area-map asset manifest exists");
        AssertTrue(File.Exists(roomsPath), "area-map room-placement inventory exists");
        using JsonDocument manifest = JsonDocument.Parse(File.ReadAllText(manifestPath));
        using JsonDocument rooms = JsonDocument.Parse(File.ReadAllText(roomsPath));
        AssertEqual(1, manifest.RootElement.GetProperty("FormatVersion").GetInt32(),
            "area-map asset format version");
        AssertEqual(AreaIds.RetailCount,
            manifest.RootElement.GetProperty("Areas").GetArrayLength(),
            "area-map manifest area count");
        AssertEqual(262, rooms.RootElement.GetArrayLength(), "area-map room placement count");
        AssertTrue(rooms.RootElement.EnumerateArray().Any(room =>
                room.GetProperty("RoomHeader").GetString() == "0xA3AE" &&
                room.GetProperty("Identity").GetString() == "$01/$26" &&
                room.GetProperty("Area").GetString() == nameof(AreaId.Brinstar)),
            "Alpha Power Bomb room placement is decoded from its room header");

        string romPath = Path.GetFullPath("Super Metroid.smc");
        if (!File.Exists(romPath))
        {
            Console.WriteLine(
                "  Area maps: committed manifest/room inventory pass; ROM byte comparison skipped.");
            return;
        }

        SuperMetroidAddressSpace bus = SuperMetroidAddressSpace.LoadRetailRom(romPath);
        JsonElement[] manifestAreas = manifest.RootElement.GetProperty("Areas")
            .EnumerateArray()
            .ToArray();
        foreach (AreaId area in Enum.GetValues<AreaId>())
        {
            int index = AreaIds.ToIndex(area);
            AreaMapCartridgeData map = AreaMapRomData.Load(bus, area);
            JsonElement record = manifestAreas[index];
            AssertEqual(area.ToString(), record.GetProperty("Area").GetString(),
                $"{area} map manifest identity");
            AssertEqual(AreaMapAssetVerificationDefinitions.TilemapAddresses[index],
                map.TilemapAddress,
                $"{area} tilemap address");

            string tilemapPath = Path.Combine(
                root,
                record.GetProperty("TilemapFile").GetString()!.Replace('/', Path.DirectorySeparatorChar));
            string revealPath = Path.Combine(
                root,
                record.GetProperty("StationRevealMaskFile").GetString()!
                    .Replace('/', Path.DirectorySeparatorChar));
            AssertSequenceEqual(map.RawTilemapBytes, File.ReadAllBytes(tilemapPath),
                $"{area} extracted tilemap bytes");
            AssertSequenceEqual(map.StationRevealMaskBytes, File.ReadAllBytes(revealPath),
                $"{area} extracted station mask bytes");

            int publicCount = 0;
            int secretCount = 0;
            for (int y = 0; y < AreaMapLayout.HeightInTiles; y++)
            {
                for (int x = 0; x < AreaMapLayout.WidthInTiles; x++)
                {
                    bool discoverable = map.IsDiscoverable(x, y);
                    bool stationVisible = map.IsRevealedByMapStation(x, y);
                    AssertTrue(!stationVisible || discoverable,
                        $"{area} station mask cell ({x},{y}) exists in tilemap");
                    publicCount += stationVisible ? 1 : 0;
                    secretCount += discoverable && !stationVisible ? 1 : 0;
                }
            }
            AssertEqual(AreaMapAssetVerificationDefinitions.StationVisibleCellCounts[index],
                publicCount,
                $"{area} station-visible cell count");
            AssertEqual(AreaMapAssetVerificationDefinitions.SecretOnlyCellCounts[index],
                secretCount,
                $"{area} secret-only cell count");
        }

        AreaMapCartridgeData brinstar = AreaMapRomData.Load(bus, AreaId.Brinstar);
        AssertTrue(brinstar.IsRevealedByMapStation(9, 1),
            "representative Brinstar public map cell");
        AssertTrue(brinstar.IsDiscoverable(23, 2) &&
                   !brinstar.IsRevealedByMapStation(23, 2),
            "representative Brinstar secret-only map cell");
        Console.WriteLine(
            "  Area maps: seven tilemaps/masks, coverage counts, and 262 room placements agree.");
    }
}
