using System.Runtime.InteropServices;
using System.Security.Cryptography;
using SuperMetroid.Core.Frontend;
using SuperMetroid.Core.Hardware;
using SuperMetroid.Core.Rendering;
using SuperMetroid.Rendering.Direct3D11;

/// <summary>Independent emulator pixels, not a golden generated by the managed renderer.</summary>
internal static class StartupReferenceTests
{
    internal static void Run(D3D11RenderDevice device, D3D11FrameRenderer renderer, byte[] rom)
    {
        var title = new TitleSequenceState(new SuperMetroidAddressSpace(rom));
        SuperMetroid.Core.Assets.Rgba32[]? lastPixels = null;
        int maximumGlyphRed = 0;
        byte[] channelBytes = new byte[FrontendFrame.Width * FrontendFrame.Height * 4];
        // Match within the named hold phase, not an assumed wall-clock startup tick.
        // This proves one visual state; it does not establish cartridge timing parity.
        for (int tick = 0; tick < 600 && title.Phase == TitleSequencePhase.YearText; tick++)
        {
            var pixels = title.Render();
            lastPixels = pixels;
            maximumGlyphRed = Math.Max(maximumGlyphRed, pixels.Max(pixel => (int)pixel.R));
            // Prove the hash uses explicit RGBA channel order rather than relying
            // silently on a record struct's in-memory representation.
            for (int pixelIndex = 0; pixelIndex < pixels.Length; pixelIndex++)
            {
                var pixel = pixels[pixelIndex];
                int offset = pixelIndex * 4;
                channelBytes[offset] = pixel.R;
                channelBytes[offset + 1] = pixel.G;
                channelBytes[offset + 2] = pixel.B;
                channelBytes[offset + 3] = pixel.A;
            }
            if (!channelBytes.AsSpan().SequenceEqual(MemoryMarshal.AsBytes(pixels.AsSpan())))
                throw new InvalidOperationException("RGBA memory layout differs from explicit channel encoding.");
            string digest = Convert.ToHexString(SHA256.HashData(MemoryMarshal.AsBytes(pixels.AsSpan())));
            if (digest == StartupReferenceData.YearRgbaSha256)
            {
                var packet = new RenderFrameSnapshot(new(tick + 1, 1, (ushort)tick), title.CaptureRenderSnapshot());
                PixelComparison.Verify(packet, pixels, renderer.RenderForReadback(packet),
                    $"{device.Kind}: independent Snes9x 1994 reference at managed tick {tick}");
                Console.WriteLine($"{device.Kind}: native Snes9x 1994 RGBA reference matches managed/GPU at tick {tick}.");
                return;
            }
            title.Step(0);
        }
        string directory = Path.GetFullPath(Path.Combine("csharp", "test-temp", "render-comparison", Guid.NewGuid().ToString("N")));
        Directory.CreateDirectory(directory);
        if (lastPixels is not null) SuperMetroid.Core.Assets.PngWriter.WriteRgba(Path.Combine(directory, "managed-year.png"), 256, 224, lastPixels);
        throw new InvalidOperationException($"Managed YearText never matched the preserved independent Snes9x pixels. Maximum red during phase: {maximumGlyphRed}. Last phase frame: {directory}");
    }
}

internal static class StartupReferenceData
{
    /// <summary>SHA-256 of row-major RGBA8 decoded from issue-321-snes9x-startup/1994.png (256x224), not PNG file bytes.</summary>
    internal const string YearRgbaSha256 = "6F57F4B36C71E9112DE91312B6EDAAD0004D676C4C38B9EB61F0D399C88771A8";
}
